// Code generated by ent, DO NOT EDIT.

package promointelsource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldName, v))
}

// Vendor applies equality check predicate on the "vendor" field. It's identical to VendorEQ.
func Vendor(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldVendor, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldCategory, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldURL, v))
}

// FetchIntervalMinutes applies equality check predicate on the "fetch_interval_minutes" field. It's identical to FetchIntervalMinutesEQ.
func FetchIntervalMinutes(v int) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldFetchIntervalMinutes, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldEnabled, v))
}

// LlmExtract applies equality check predicate on the "llm_extract" field. It's identical to LlmExtractEQ.
func LlmExtract(v bool) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldLlmExtract, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldNotes, v))
}

// LastFetchedAt applies equality check predicate on the "last_fetched_at" field. It's identical to LastFetchedAtEQ.
func LastFetchedAt(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldLastFetchedAt, v))
}

// LastExtractedHash applies equality check predicate on the "last_extracted_hash" field. It's identical to LastExtractedHashEQ.
func LastExtractedHash(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldLastExtractedHash, v))
}

// LastStatus applies equality check predicate on the "last_status" field. It's identical to LastStatusEQ.
func LastStatus(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldLastStatus, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldLastError, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContainsFold(FieldName, v))
}

// VendorEQ applies the EQ predicate on the "vendor" field.
func VendorEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldVendor, v))
}

// VendorNEQ applies the NEQ predicate on the "vendor" field.
func VendorNEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldVendor, v))
}

// VendorIn applies the In predicate on the "vendor" field.
func VendorIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldVendor, vs...))
}

// VendorNotIn applies the NotIn predicate on the "vendor" field.
func VendorNotIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldVendor, vs...))
}

// VendorGT applies the GT predicate on the "vendor" field.
func VendorGT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldVendor, v))
}

// VendorGTE applies the GTE predicate on the "vendor" field.
func VendorGTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldVendor, v))
}

// VendorLT applies the LT predicate on the "vendor" field.
func VendorLT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldVendor, v))
}

// VendorLTE applies the LTE predicate on the "vendor" field.
func VendorLTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldVendor, v))
}

// VendorContains applies the Contains predicate on the "vendor" field.
func VendorContains(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContains(FieldVendor, v))
}

// VendorHasPrefix applies the HasPrefix predicate on the "vendor" field.
func VendorHasPrefix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasPrefix(FieldVendor, v))
}

// VendorHasSuffix applies the HasSuffix predicate on the "vendor" field.
func VendorHasSuffix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasSuffix(FieldVendor, v))
}

// VendorEqualFold applies the EqualFold predicate on the "vendor" field.
func VendorEqualFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEqualFold(FieldVendor, v))
}

// VendorContainsFold applies the ContainsFold predicate on the "vendor" field.
func VendorContainsFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContainsFold(FieldVendor, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContainsFold(FieldCategory, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContainsFold(FieldURL, v))
}

// FetchIntervalMinutesEQ applies the EQ predicate on the "fetch_interval_minutes" field.
func FetchIntervalMinutesEQ(v int) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldFetchIntervalMinutes, v))
}

// FetchIntervalMinutesNEQ applies the NEQ predicate on the "fetch_interval_minutes" field.
func FetchIntervalMinutesNEQ(v int) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldFetchIntervalMinutes, v))
}

// FetchIntervalMinutesIn applies the In predicate on the "fetch_interval_minutes" field.
func FetchIntervalMinutesIn(vs ...int) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldFetchIntervalMinutes, vs...))
}

// FetchIntervalMinutesNotIn applies the NotIn predicate on the "fetch_interval_minutes" field.
func FetchIntervalMinutesNotIn(vs ...int) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldFetchIntervalMinutes, vs...))
}

// FetchIntervalMinutesGT applies the GT predicate on the "fetch_interval_minutes" field.
func FetchIntervalMinutesGT(v int) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldFetchIntervalMinutes, v))
}

// FetchIntervalMinutesGTE applies the GTE predicate on the "fetch_interval_minutes" field.
func FetchIntervalMinutesGTE(v int) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldFetchIntervalMinutes, v))
}

// FetchIntervalMinutesLT applies the LT predicate on the "fetch_interval_minutes" field.
func FetchIntervalMinutesLT(v int) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldFetchIntervalMinutes, v))
}

// FetchIntervalMinutesLTE applies the LTE predicate on the "fetch_interval_minutes" field.
func FetchIntervalMinutesLTE(v int) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldFetchIntervalMinutes, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldEnabled, v))
}

// LlmExtractEQ applies the EQ predicate on the "llm_extract" field.
func LlmExtractEQ(v bool) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldLlmExtract, v))
}

// LlmExtractNEQ applies the NEQ predicate on the "llm_extract" field.
func LlmExtractNEQ(v bool) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldLlmExtract, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContainsFold(FieldNotes, v))
}

// LastFetchedAtEQ applies the EQ predicate on the "last_fetched_at" field.
func LastFetchedAtEQ(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldLastFetchedAt, v))
}

// LastFetchedAtNEQ applies the NEQ predicate on the "last_fetched_at" field.
func LastFetchedAtNEQ(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldLastFetchedAt, v))
}

// LastFetchedAtIn applies the In predicate on the "last_fetched_at" field.
func LastFetchedAtIn(vs ...time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldLastFetchedAt, vs...))
}

// LastFetchedAtNotIn applies the NotIn predicate on the "last_fetched_at" field.
func LastFetchedAtNotIn(vs ...time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldLastFetchedAt, vs...))
}

// LastFetchedAtGT applies the GT predicate on the "last_fetched_at" field.
func LastFetchedAtGT(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldLastFetchedAt, v))
}

// LastFetchedAtGTE applies the GTE predicate on the "last_fetched_at" field.
func LastFetchedAtGTE(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldLastFetchedAt, v))
}

// LastFetchedAtLT applies the LT predicate on the "last_fetched_at" field.
func LastFetchedAtLT(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldLastFetchedAt, v))
}

// LastFetchedAtLTE applies the LTE predicate on the "last_fetched_at" field.
func LastFetchedAtLTE(v time.Time) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldLastFetchedAt, v))
}

// LastFetchedAtIsNil applies the IsNil predicate on the "last_fetched_at" field.
func LastFetchedAtIsNil() predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIsNull(FieldLastFetchedAt))
}

// LastFetchedAtNotNil applies the NotNil predicate on the "last_fetched_at" field.
func LastFetchedAtNotNil() predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotNull(FieldLastFetchedAt))
}

// LastExtractedHashEQ applies the EQ predicate on the "last_extracted_hash" field.
func LastExtractedHashEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldLastExtractedHash, v))
}

// LastExtractedHashNEQ applies the NEQ predicate on the "last_extracted_hash" field.
func LastExtractedHashNEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldLastExtractedHash, v))
}

// LastExtractedHashIn applies the In predicate on the "last_extracted_hash" field.
func LastExtractedHashIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldLastExtractedHash, vs...))
}

// LastExtractedHashNotIn applies the NotIn predicate on the "last_extracted_hash" field.
func LastExtractedHashNotIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldLastExtractedHash, vs...))
}

// LastExtractedHashGT applies the GT predicate on the "last_extracted_hash" field.
func LastExtractedHashGT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldLastExtractedHash, v))
}

// LastExtractedHashGTE applies the GTE predicate on the "last_extracted_hash" field.
func LastExtractedHashGTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldLastExtractedHash, v))
}

// LastExtractedHashLT applies the LT predicate on the "last_extracted_hash" field.
func LastExtractedHashLT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldLastExtractedHash, v))
}

// LastExtractedHashLTE applies the LTE predicate on the "last_extracted_hash" field.
func LastExtractedHashLTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldLastExtractedHash, v))
}

// LastExtractedHashContains applies the Contains predicate on the "last_extracted_hash" field.
func LastExtractedHashContains(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContains(FieldLastExtractedHash, v))
}

// LastExtractedHashHasPrefix applies the HasPrefix predicate on the "last_extracted_hash" field.
func LastExtractedHashHasPrefix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasPrefix(FieldLastExtractedHash, v))
}

// LastExtractedHashHasSuffix applies the HasSuffix predicate on the "last_extracted_hash" field.
func LastExtractedHashHasSuffix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasSuffix(FieldLastExtractedHash, v))
}

// LastExtractedHashEqualFold applies the EqualFold predicate on the "last_extracted_hash" field.
func LastExtractedHashEqualFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEqualFold(FieldLastExtractedHash, v))
}

// LastExtractedHashContainsFold applies the ContainsFold predicate on the "last_extracted_hash" field.
func LastExtractedHashContainsFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContainsFold(FieldLastExtractedHash, v))
}

// LastStatusEQ applies the EQ predicate on the "last_status" field.
func LastStatusEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldLastStatus, v))
}

// LastStatusNEQ applies the NEQ predicate on the "last_status" field.
func LastStatusNEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldLastStatus, v))
}

// LastStatusIn applies the In predicate on the "last_status" field.
func LastStatusIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldLastStatus, vs...))
}

// LastStatusNotIn applies the NotIn predicate on the "last_status" field.
func LastStatusNotIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldLastStatus, vs...))
}

// LastStatusGT applies the GT predicate on the "last_status" field.
func LastStatusGT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldLastStatus, v))
}

// LastStatusGTE applies the GTE predicate on the "last_status" field.
func LastStatusGTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldLastStatus, v))
}

// LastStatusLT applies the LT predicate on the "last_status" field.
func LastStatusLT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldLastStatus, v))
}

// LastStatusLTE applies the LTE predicate on the "last_status" field.
func LastStatusLTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldLastStatus, v))
}

// LastStatusContains applies the Contains predicate on the "last_status" field.
func LastStatusContains(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContains(FieldLastStatus, v))
}

// LastStatusHasPrefix applies the HasPrefix predicate on the "last_status" field.
func LastStatusHasPrefix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasPrefix(FieldLastStatus, v))
}

// LastStatusHasSuffix applies the HasSuffix predicate on the "last_status" field.
func LastStatusHasSuffix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasSuffix(FieldLastStatus, v))
}

// LastStatusEqualFold applies the EqualFold predicate on the "last_status" field.
func LastStatusEqualFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEqualFold(FieldLastStatus, v))
}

// LastStatusContainsFold applies the ContainsFold predicate on the "last_status" field.
func LastStatusContainsFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContainsFold(FieldLastStatus, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.FieldLTE(FieldCreatedBy, v))
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.PromoIntelSource {
	return predicate.PromoIntelSource(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.PromoIntelItem) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromoIntelSource) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromoIntelSource) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromoIntelSource) predicate.PromoIntelSource {
	return predicate.PromoIntelSource(sql.NotPredicates(p))
}
