// Code generated by ent, DO NOT EDIT.

package promointelitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldSourceID, v))
}

// Vendor applies equality check predicate on the "vendor" field. It's identical to VendorEQ.
func Vendor(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldVendor, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldCategory, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldTitle, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldSummary, v))
}

// Details applies equality check predicate on the "details" field. It's identical to DetailsEQ.
func Details(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldDetails, v))
}

// DiscountInfo applies equality check predicate on the "discount_info" field. It's identical to DiscountInfoEQ.
func DiscountInfo(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldDiscountInfo, v))
}

// ValidUntil applies equality check predicate on the "valid_until" field. It's identical to ValidUntilEQ.
func ValidUntil(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldValidUntil, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldURL, v))
}

// Relevance applies equality check predicate on the "relevance" field. It's identical to RelevanceEQ.
func Relevance(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldRelevance, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldStatus, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldFingerprint, v))
}

// RawExcerpt applies equality check predicate on the "raw_excerpt" field. It's identical to RawExcerptEQ.
func RawExcerpt(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldRawExcerpt, v))
}

// ExtractStatus applies equality check predicate on the "extract_status" field. It's identical to ExtractStatusEQ.
func ExtractStatus(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldExtractStatus, v))
}

// DigestDate applies equality check predicate on the "digest_date" field. It's identical to DigestDateEQ.
func DigestDate(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldDigestDate, v))
}

// SourceFetchedAt applies equality check predicate on the "source_fetched_at" field. It's identical to SourceFetchedAtEQ.
func SourceFetchedAt(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldSourceFetchedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldSourceID, vs...))
}

// VendorEQ applies the EQ predicate on the "vendor" field.
func VendorEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldVendor, v))
}

// VendorNEQ applies the NEQ predicate on the "vendor" field.
func VendorNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldVendor, v))
}

// VendorIn applies the In predicate on the "vendor" field.
func VendorIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldVendor, vs...))
}

// VendorNotIn applies the NotIn predicate on the "vendor" field.
func VendorNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldVendor, vs...))
}

// VendorGT applies the GT predicate on the "vendor" field.
func VendorGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldVendor, v))
}

// VendorGTE applies the GTE predicate on the "vendor" field.
func VendorGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldVendor, v))
}

// VendorLT applies the LT predicate on the "vendor" field.
func VendorLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldVendor, v))
}

// VendorLTE applies the LTE predicate on the "vendor" field.
func VendorLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldVendor, v))
}

// VendorContains applies the Contains predicate on the "vendor" field.
func VendorContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldVendor, v))
}

// VendorHasPrefix applies the HasPrefix predicate on the "vendor" field.
func VendorHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldVendor, v))
}

// VendorHasSuffix applies the HasSuffix predicate on the "vendor" field.
func VendorHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldVendor, v))
}

// VendorEqualFold applies the EqualFold predicate on the "vendor" field.
func VendorEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldVendor, v))
}

// VendorContainsFold applies the ContainsFold predicate on the "vendor" field.
func VendorContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldVendor, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldCategory, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldTitle, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldSummary, v))
}

// DetailsEQ applies the EQ predicate on the "details" field.
func DetailsEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldDetails, v))
}

// DetailsNEQ applies the NEQ predicate on the "details" field.
func DetailsNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldDetails, v))
}

// DetailsIn applies the In predicate on the "details" field.
func DetailsIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldDetails, vs...))
}

// DetailsNotIn applies the NotIn predicate on the "details" field.
func DetailsNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldDetails, vs...))
}

// DetailsGT applies the GT predicate on the "details" field.
func DetailsGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldDetails, v))
}

// DetailsGTE applies the GTE predicate on the "details" field.
func DetailsGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldDetails, v))
}

// DetailsLT applies the LT predicate on the "details" field.
func DetailsLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldDetails, v))
}

// DetailsLTE applies the LTE predicate on the "details" field.
func DetailsLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldDetails, v))
}

// DetailsContains applies the Contains predicate on the "details" field.
func DetailsContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldDetails, v))
}

// DetailsHasPrefix applies the HasPrefix predicate on the "details" field.
func DetailsHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldDetails, v))
}

// DetailsHasSuffix applies the HasSuffix predicate on the "details" field.
func DetailsHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldDetails, v))
}

// DetailsEqualFold applies the EqualFold predicate on the "details" field.
func DetailsEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldDetails, v))
}

// DetailsContainsFold applies the ContainsFold predicate on the "details" field.
func DetailsContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldDetails, v))
}

// DiscountInfoEQ applies the EQ predicate on the "discount_info" field.
func DiscountInfoEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldDiscountInfo, v))
}

// DiscountInfoNEQ applies the NEQ predicate on the "discount_info" field.
func DiscountInfoNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldDiscountInfo, v))
}

// DiscountInfoIn applies the In predicate on the "discount_info" field.
func DiscountInfoIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldDiscountInfo, vs...))
}

// DiscountInfoNotIn applies the NotIn predicate on the "discount_info" field.
func DiscountInfoNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldDiscountInfo, vs...))
}

// DiscountInfoGT applies the GT predicate on the "discount_info" field.
func DiscountInfoGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldDiscountInfo, v))
}

// DiscountInfoGTE applies the GTE predicate on the "discount_info" field.
func DiscountInfoGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldDiscountInfo, v))
}

// DiscountInfoLT applies the LT predicate on the "discount_info" field.
func DiscountInfoLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldDiscountInfo, v))
}

// DiscountInfoLTE applies the LTE predicate on the "discount_info" field.
func DiscountInfoLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldDiscountInfo, v))
}

// DiscountInfoContains applies the Contains predicate on the "discount_info" field.
func DiscountInfoContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldDiscountInfo, v))
}

// DiscountInfoHasPrefix applies the HasPrefix predicate on the "discount_info" field.
func DiscountInfoHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldDiscountInfo, v))
}

// DiscountInfoHasSuffix applies the HasSuffix predicate on the "discount_info" field.
func DiscountInfoHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldDiscountInfo, v))
}

// DiscountInfoEqualFold applies the EqualFold predicate on the "discount_info" field.
func DiscountInfoEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldDiscountInfo, v))
}

// DiscountInfoContainsFold applies the ContainsFold predicate on the "discount_info" field.
func DiscountInfoContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldDiscountInfo, v))
}

// ValidUntilEQ applies the EQ predicate on the "valid_until" field.
func ValidUntilEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldValidUntil, v))
}

// ValidUntilNEQ applies the NEQ predicate on the "valid_until" field.
func ValidUntilNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldValidUntil, v))
}

// ValidUntilIn applies the In predicate on the "valid_until" field.
func ValidUntilIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldValidUntil, vs...))
}

// ValidUntilNotIn applies the NotIn predicate on the "valid_until" field.
func ValidUntilNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldValidUntil, vs...))
}

// ValidUntilGT applies the GT predicate on the "valid_until" field.
func ValidUntilGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldValidUntil, v))
}

// ValidUntilGTE applies the GTE predicate on the "valid_until" field.
func ValidUntilGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldValidUntil, v))
}

// ValidUntilLT applies the LT predicate on the "valid_until" field.
func ValidUntilLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldValidUntil, v))
}

// ValidUntilLTE applies the LTE predicate on the "valid_until" field.
func ValidUntilLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldValidUntil, v))
}

// ValidUntilContains applies the Contains predicate on the "valid_until" field.
func ValidUntilContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldValidUntil, v))
}

// ValidUntilHasPrefix applies the HasPrefix predicate on the "valid_until" field.
func ValidUntilHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldValidUntil, v))
}

// ValidUntilHasSuffix applies the HasSuffix predicate on the "valid_until" field.
func ValidUntilHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldValidUntil, v))
}

// ValidUntilEqualFold applies the EqualFold predicate on the "valid_until" field.
func ValidUntilEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldValidUntil, v))
}

// ValidUntilContainsFold applies the ContainsFold predicate on the "valid_until" field.
func ValidUntilContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldValidUntil, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldURL, v))
}

// RelevanceEQ applies the EQ predicate on the "relevance" field.
func RelevanceEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldRelevance, v))
}

// RelevanceNEQ applies the NEQ predicate on the "relevance" field.
func RelevanceNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldRelevance, v))
}

// RelevanceIn applies the In predicate on the "relevance" field.
func RelevanceIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldRelevance, vs...))
}

// RelevanceNotIn applies the NotIn predicate on the "relevance" field.
func RelevanceNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldRelevance, vs...))
}

// RelevanceGT applies the GT predicate on the "relevance" field.
func RelevanceGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldRelevance, v))
}

// RelevanceGTE applies the GTE predicate on the "relevance" field.
func RelevanceGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldRelevance, v))
}

// RelevanceLT applies the LT predicate on the "relevance" field.
func RelevanceLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldRelevance, v))
}

// RelevanceLTE applies the LTE predicate on the "relevance" field.
func RelevanceLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldRelevance, v))
}

// RelevanceContains applies the Contains predicate on the "relevance" field.
func RelevanceContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldRelevance, v))
}

// RelevanceHasPrefix applies the HasPrefix predicate on the "relevance" field.
func RelevanceHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldRelevance, v))
}

// RelevanceHasSuffix applies the HasSuffix predicate on the "relevance" field.
func RelevanceHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldRelevance, v))
}

// RelevanceEqualFold applies the EqualFold predicate on the "relevance" field.
func RelevanceEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldRelevance, v))
}

// RelevanceContainsFold applies the ContainsFold predicate on the "relevance" field.
func RelevanceContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldRelevance, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldStatus, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldFingerprint, v))
}

// RawExcerptEQ applies the EQ predicate on the "raw_excerpt" field.
func RawExcerptEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldRawExcerpt, v))
}

// RawExcerptNEQ applies the NEQ predicate on the "raw_excerpt" field.
func RawExcerptNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldRawExcerpt, v))
}

// RawExcerptIn applies the In predicate on the "raw_excerpt" field.
func RawExcerptIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldRawExcerpt, vs...))
}

// RawExcerptNotIn applies the NotIn predicate on the "raw_excerpt" field.
func RawExcerptNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldRawExcerpt, vs...))
}

// RawExcerptGT applies the GT predicate on the "raw_excerpt" field.
func RawExcerptGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldRawExcerpt, v))
}

// RawExcerptGTE applies the GTE predicate on the "raw_excerpt" field.
func RawExcerptGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldRawExcerpt, v))
}

// RawExcerptLT applies the LT predicate on the "raw_excerpt" field.
func RawExcerptLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldRawExcerpt, v))
}

// RawExcerptLTE applies the LTE predicate on the "raw_excerpt" field.
func RawExcerptLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldRawExcerpt, v))
}

// RawExcerptContains applies the Contains predicate on the "raw_excerpt" field.
func RawExcerptContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldRawExcerpt, v))
}

// RawExcerptHasPrefix applies the HasPrefix predicate on the "raw_excerpt" field.
func RawExcerptHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldRawExcerpt, v))
}

// RawExcerptHasSuffix applies the HasSuffix predicate on the "raw_excerpt" field.
func RawExcerptHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldRawExcerpt, v))
}

// RawExcerptEqualFold applies the EqualFold predicate on the "raw_excerpt" field.
func RawExcerptEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldRawExcerpt, v))
}

// RawExcerptContainsFold applies the ContainsFold predicate on the "raw_excerpt" field.
func RawExcerptContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldRawExcerpt, v))
}

// ExtractStatusEQ applies the EQ predicate on the "extract_status" field.
func ExtractStatusEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldExtractStatus, v))
}

// ExtractStatusNEQ applies the NEQ predicate on the "extract_status" field.
func ExtractStatusNEQ(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldExtractStatus, v))
}

// ExtractStatusIn applies the In predicate on the "extract_status" field.
func ExtractStatusIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldExtractStatus, vs...))
}

// ExtractStatusNotIn applies the NotIn predicate on the "extract_status" field.
func ExtractStatusNotIn(vs ...string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldExtractStatus, vs...))
}

// ExtractStatusGT applies the GT predicate on the "extract_status" field.
func ExtractStatusGT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldExtractStatus, v))
}

// ExtractStatusGTE applies the GTE predicate on the "extract_status" field.
func ExtractStatusGTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldExtractStatus, v))
}

// ExtractStatusLT applies the LT predicate on the "extract_status" field.
func ExtractStatusLT(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldExtractStatus, v))
}

// ExtractStatusLTE applies the LTE predicate on the "extract_status" field.
func ExtractStatusLTE(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldExtractStatus, v))
}

// ExtractStatusContains applies the Contains predicate on the "extract_status" field.
func ExtractStatusContains(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContains(FieldExtractStatus, v))
}

// ExtractStatusHasPrefix applies the HasPrefix predicate on the "extract_status" field.
func ExtractStatusHasPrefix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasPrefix(FieldExtractStatus, v))
}

// ExtractStatusHasSuffix applies the HasSuffix predicate on the "extract_status" field.
func ExtractStatusHasSuffix(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldHasSuffix(FieldExtractStatus, v))
}

// ExtractStatusEqualFold applies the EqualFold predicate on the "extract_status" field.
func ExtractStatusEqualFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEqualFold(FieldExtractStatus, v))
}

// ExtractStatusContainsFold applies the ContainsFold predicate on the "extract_status" field.
func ExtractStatusContainsFold(v string) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldContainsFold(FieldExtractStatus, v))
}

// DigestDateEQ applies the EQ predicate on the "digest_date" field.
func DigestDateEQ(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldDigestDate, v))
}

// DigestDateNEQ applies the NEQ predicate on the "digest_date" field.
func DigestDateNEQ(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldDigestDate, v))
}

// DigestDateIn applies the In predicate on the "digest_date" field.
func DigestDateIn(vs ...time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldDigestDate, vs...))
}

// DigestDateNotIn applies the NotIn predicate on the "digest_date" field.
func DigestDateNotIn(vs ...time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldDigestDate, vs...))
}

// DigestDateGT applies the GT predicate on the "digest_date" field.
func DigestDateGT(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldDigestDate, v))
}

// DigestDateGTE applies the GTE predicate on the "digest_date" field.
func DigestDateGTE(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldDigestDate, v))
}

// DigestDateLT applies the LT predicate on the "digest_date" field.
func DigestDateLT(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldDigestDate, v))
}

// DigestDateLTE applies the LTE predicate on the "digest_date" field.
func DigestDateLTE(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldDigestDate, v))
}

// DigestDateIsNil applies the IsNil predicate on the "digest_date" field.
func DigestDateIsNil() predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIsNull(FieldDigestDate))
}

// DigestDateNotNil applies the NotNil predicate on the "digest_date" field.
func DigestDateNotNil() predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotNull(FieldDigestDate))
}

// SourceFetchedAtEQ applies the EQ predicate on the "source_fetched_at" field.
func SourceFetchedAtEQ(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldEQ(FieldSourceFetchedAt, v))
}

// SourceFetchedAtNEQ applies the NEQ predicate on the "source_fetched_at" field.
func SourceFetchedAtNEQ(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNEQ(FieldSourceFetchedAt, v))
}

// SourceFetchedAtIn applies the In predicate on the "source_fetched_at" field.
func SourceFetchedAtIn(vs ...time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldIn(FieldSourceFetchedAt, vs...))
}

// SourceFetchedAtNotIn applies the NotIn predicate on the "source_fetched_at" field.
func SourceFetchedAtNotIn(vs ...time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldNotIn(FieldSourceFetchedAt, vs...))
}

// SourceFetchedAtGT applies the GT predicate on the "source_fetched_at" field.
func SourceFetchedAtGT(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGT(FieldSourceFetchedAt, v))
}

// SourceFetchedAtGTE applies the GTE predicate on the "source_fetched_at" field.
func SourceFetchedAtGTE(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldGTE(FieldSourceFetchedAt, v))
}

// SourceFetchedAtLT applies the LT predicate on the "source_fetched_at" field.
func SourceFetchedAtLT(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLT(FieldSourceFetchedAt, v))
}

// SourceFetchedAtLTE applies the LTE predicate on the "source_fetched_at" field.
func SourceFetchedAtLTE(v time.Time) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.FieldLTE(FieldSourceFetchedAt, v))
}

// HasSource applies the HasEdge predicate on the "source" edge.
func HasSource() predicate.PromoIntelItem {
	return predicate.PromoIntelItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceTable, SourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceWith applies the HasEdge predicate on the "source" edge with a given conditions (other predicates).
func HasSourceWith(preds ...predicate.PromoIntelSource) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(func(s *sql.Selector) {
		step := newSourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromoIntelItem) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromoIntelItem) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromoIntelItem) predicate.PromoIntelItem {
	return predicate.PromoIntelItem(sql.NotPredicates(p))
}
