// Code generated by ent, DO NOT EDIT.

package redeemcodegroup

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the redeemcodegroup type in the database.
	Label = "redeem_code_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRedeemCodeID holds the string denoting the redeem_code_id field in the database.
	FieldRedeemCodeID = "redeem_code_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldValidityDays holds the string denoting the validity_days field in the database.
	FieldValidityDays = "validity_days"
	// EdgeRedeemCode holds the string denoting the redeem_code edge name in mutations.
	EdgeRedeemCode = "redeem_code"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the redeemcodegroup in the database.
	Table = "redeem_code_groups"
	// RedeemCodeTable is the table that holds the redeem_code relation/edge.
	RedeemCodeTable = "redeem_code_groups"
	// RedeemCodeInverseTable is the table name for the RedeemCode entity.
	// It exists in this package in order to avoid circular dependency with the "redeemcode" package.
	RedeemCodeInverseTable = "redeem_codes"
	// RedeemCodeColumn is the table column denoting the redeem_code relation/edge.
	RedeemCodeColumn = "redeem_code_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "redeem_code_groups"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for redeemcodegroup fields.
var Columns = []string{
	FieldID,
	FieldRedeemCodeID,
	FieldGroupID,
	FieldValidityDays,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultValidityDays holds the default value on creation for the "validity_days" field.
	DefaultValidityDays int
)

// OrderOption defines the ordering options for the RedeemCodeGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRedeemCodeID orders the results by the redeem_code_id field.
func ByRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemCodeID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByValidityDays orders the results by the validity_days field.
func ByValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityDays, opts...).ToFunc()
}

// ByRedeemCodeField orders the results by redeem_code field.
func ByRedeemCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRedeemCodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newRedeemCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RedeemCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RedeemCodeTable, RedeemCodeColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
