// Code generated by ent, DO NOT EDIT.

package redeemcodegroup

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldLTE(FieldID, id))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldEQ(FieldRedeemCodeID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldEQ(FieldGroupID, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldEQ(FieldValidityDays, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldNotIn(FieldGroupID, vs...))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.FieldLTE(FieldValidityDays, v))
}

// HasRedeemCode applies the HasEdge predicate on the "redeem_code" edge.
func HasRedeemCode() predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RedeemCodeTable, RedeemCodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRedeemCodeWith applies the HasEdge predicate on the "redeem_code" edge with a given conditions (other predicates).
func HasRedeemCodeWith(preds ...predicate.RedeemCode) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(func(s *sql.Selector) {
		step := newRedeemCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedeemCodeGroup) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedeemCodeGroup) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedeemCodeGroup) predicate.RedeemCodeGroup {
	return predicate.RedeemCodeGroup(sql.NotPredicates(p))
}
