// Code generated by ent, DO NOT EDIT.

package usageriskrun

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usageriskrun type in the database.
	Label = "usage_risk_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "run_id"
	// FieldRunAt holds the string denoting the run_at field in the database.
	FieldRunAt = "run_at"
	// FieldWindowStart holds the string denoting the window_start field in the database.
	FieldWindowStart = "window_start"
	// FieldWindowEnd holds the string denoting the window_end field in the database.
	FieldWindowEnd = "window_end"
	// FieldCandidatesTotal holds the string denoting the candidates_total field in the database.
	FieldCandidatesTotal = "candidates_total"
	// FieldBatchesDone holds the string denoting the batches_done field in the database.
	FieldBatchesDone = "batches_done"
	// FieldBatchesFailed holds the string denoting the batches_failed field in the database.
	FieldBatchesFailed = "batches_failed"
	// FieldFailedBatches holds the string denoting the failed_batches field in the database.
	FieldFailedBatches = "failed_batches"
	// FieldBudgetExhausted holds the string denoting the budget_exhausted field in the database.
	FieldBudgetExhausted = "budget_exhausted"
	// FieldReconCursorDate holds the string denoting the recon_cursor_date field in the database.
	FieldReconCursorDate = "recon_cursor_date"
	// FieldReconBatchOffset holds the string denoting the recon_batch_offset field in the database.
	FieldReconBatchOffset = "recon_batch_offset"
	// FieldReconBatchesDone holds the string denoting the recon_batches_done field in the database.
	FieldReconBatchesDone = "recon_batches_done"
	// FieldConsecutivePartials holds the string denoting the consecutive_partials field in the database.
	FieldConsecutivePartials = "consecutive_partials"
	// FieldPolicyVersion holds the string denoting the policy_version field in the database.
	FieldPolicyVersion = "policy_version"
	// FieldR1ReevalPending holds the string denoting the r1_reeval_pending field in the database.
	FieldR1ReevalPending = "r1_reeval_pending"
	// FieldPolicySnapshot holds the string denoting the policy_snapshot field in the database.
	FieldPolicySnapshot = "policy_snapshot"
	// FieldHistoryCovered holds the string denoting the history_covered field in the database.
	FieldHistoryCovered = "history_covered"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldFailureStage holds the string denoting the failure_stage field in the database.
	FieldFailureStage = "failure_stage"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the usageriskrun in the database.
	Table = "usage_risk_runs"
)

// Columns holds all SQL columns for usageriskrun fields.
var Columns = []string{
	FieldID,
	FieldRunAt,
	FieldWindowStart,
	FieldWindowEnd,
	FieldCandidatesTotal,
	FieldBatchesDone,
	FieldBatchesFailed,
	FieldFailedBatches,
	FieldBudgetExhausted,
	FieldReconCursorDate,
	FieldReconBatchOffset,
	FieldReconBatchesDone,
	FieldConsecutivePartials,
	FieldPolicyVersion,
	FieldR1ReevalPending,
	FieldPolicySnapshot,
	FieldHistoryCovered,
	FieldFinishedAt,
	FieldFailureStage,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCandidatesTotal holds the default value on creation for the "candidates_total" field.
	DefaultCandidatesTotal int
	// DefaultBatchesDone holds the default value on creation for the "batches_done" field.
	DefaultBatchesDone int
	// DefaultBatchesFailed holds the default value on creation for the "batches_failed" field.
	DefaultBatchesFailed int
	// DefaultBudgetExhausted holds the default value on creation for the "budget_exhausted" field.
	DefaultBudgetExhausted bool
	// DefaultReconBatchOffset holds the default value on creation for the "recon_batch_offset" field.
	DefaultReconBatchOffset int
	// DefaultReconBatchesDone holds the default value on creation for the "recon_batches_done" field.
	DefaultReconBatchesDone int
	// DefaultConsecutivePartials holds the default value on creation for the "consecutive_partials" field.
	DefaultConsecutivePartials int
	// DefaultPolicyVersion holds the default value on creation for the "policy_version" field.
	DefaultPolicyVersion int64
	// DefaultR1ReevalPending holds the default value on creation for the "r1_reeval_pending" field.
	DefaultR1ReevalPending bool
	// DefaultHistoryCovered holds the default value on creation for the "history_covered" field.
	DefaultHistoryCovered bool
	// FailureStageValidator is a validator for the "failure_stage" field. It is called by the builders before save.
	FailureStageValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the UsageRiskRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunAt orders the results by the run_at field.
func ByRunAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunAt, opts...).ToFunc()
}

// ByWindowStart orders the results by the window_start field.
func ByWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowStart, opts...).ToFunc()
}

// ByWindowEnd orders the results by the window_end field.
func ByWindowEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowEnd, opts...).ToFunc()
}

// ByCandidatesTotal orders the results by the candidates_total field.
func ByCandidatesTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCandidatesTotal, opts...).ToFunc()
}

// ByBatchesDone orders the results by the batches_done field.
func ByBatchesDone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchesDone, opts...).ToFunc()
}

// ByBatchesFailed orders the results by the batches_failed field.
func ByBatchesFailed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchesFailed, opts...).ToFunc()
}

// ByBudgetExhausted orders the results by the budget_exhausted field.
func ByBudgetExhausted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBudgetExhausted, opts...).ToFunc()
}

// ByReconCursorDate orders the results by the recon_cursor_date field.
func ByReconCursorDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReconCursorDate, opts...).ToFunc()
}

// ByReconBatchOffset orders the results by the recon_batch_offset field.
func ByReconBatchOffset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReconBatchOffset, opts...).ToFunc()
}

// ByReconBatchesDone orders the results by the recon_batches_done field.
func ByReconBatchesDone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReconBatchesDone, opts...).ToFunc()
}

// ByConsecutivePartials orders the results by the consecutive_partials field.
func ByConsecutivePartials(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutivePartials, opts...).ToFunc()
}

// ByPolicyVersion orders the results by the policy_version field.
func ByPolicyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyVersion, opts...).ToFunc()
}

// ByR1ReevalPending orders the results by the r1_reeval_pending field.
func ByR1ReevalPending(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldR1ReevalPending, opts...).ToFunc()
}

// ByHistoryCovered orders the results by the history_covered field.
func ByHistoryCovered(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHistoryCovered, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByFailureStage orders the results by the failure_stage field.
func ByFailureStage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureStage, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
