// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountmodelcapability"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountModelCapabilityDelete is the builder for deleting a AccountModelCapability entity.
type AccountModelCapabilityDelete struct {
	config
	hooks    []Hook
	mutation *AccountModelCapabilityMutation
}

// Where appends a list predicates to the AccountModelCapabilityDelete builder.
func (_d *AccountModelCapabilityDelete) Where(ps ...predicate.AccountModelCapability) *AccountModelCapabilityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountModelCapabilityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountModelCapabilityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountModelCapabilityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountmodelcapability.Table, sqlgraph.NewFieldSpec(accountmodelcapability.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountModelCapabilityDeleteOne is the builder for deleting a single AccountModelCapability entity.
type AccountModelCapabilityDeleteOne struct {
	_d *AccountModelCapabilityDelete
}

// Where appends a list predicates to the AccountModelCapabilityDelete builder.
func (_d *AccountModelCapabilityDeleteOne) Where(ps ...predicate.AccountModelCapability) *AccountModelCapabilityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountModelCapabilityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountmodelcapability.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountModelCapabilityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
