// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountmodelcapability"
)

// AccountModelCapability is the model entity for the AccountModelCapability schema.
type AccountModelCapability struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol string `json:"protocol,omitempty"`
	// SupportsVision holds the value of the "supports_vision" field.
	SupportsVision bool `json:"supports_vision,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// DetectedAt holds the value of the "detected_at" field.
	DetectedAt *time.Time `json:"detected_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountModelCapability) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountmodelcapability.FieldSupportsVision:
			values[i] = new(sql.NullBool)
		case accountmodelcapability.FieldID, accountmodelcapability.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case accountmodelcapability.FieldUpstreamModel, accountmodelcapability.FieldProtocol, accountmodelcapability.FieldSource:
			values[i] = new(sql.NullString)
		case accountmodelcapability.FieldDetectedAt, accountmodelcapability.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountModelCapability fields.
func (_m *AccountModelCapability) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountmodelcapability.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountmodelcapability.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountmodelcapability.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case accountmodelcapability.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case accountmodelcapability.FieldSupportsVision:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field supports_vision", values[i])
			} else if value.Valid {
				_m.SupportsVision = value.Bool
			}
		case accountmodelcapability.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case accountmodelcapability.FieldDetectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field detected_at", values[i])
			} else if value.Valid {
				_m.DetectedAt = new(time.Time)
				*_m.DetectedAt = value.Time
			}
		case accountmodelcapability.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountModelCapability.
// This includes values selected through modifiers, order, etc.
func (_m *AccountModelCapability) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountModelCapability.
// Note that you need to call AccountModelCapability.Unwrap() before calling this method if this AccountModelCapability
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountModelCapability) Update() *AccountModelCapabilityUpdateOne {
	return NewAccountModelCapabilityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountModelCapability entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountModelCapability) Unwrap() *AccountModelCapability {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountModelCapability is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountModelCapability) String() string {
	var builder strings.Builder
	builder.WriteString("AccountModelCapability(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("supports_vision=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupportsVision))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.DetectedAt; v != nil {
		builder.WriteString("detected_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountModelCapabilities is a parsable slice of AccountModelCapability.
type AccountModelCapabilities []*AccountModelCapability
