// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/promointelitem"
	"github.com/Wei-Shaw/sub2api/ent/promointelsource"
)

// PromoIntelSourceUpdate is the builder for updating PromoIntelSource entities.
type PromoIntelSourceUpdate struct {
	config
	hooks    []Hook
	mutation *PromoIntelSourceMutation
}

// Where appends a list predicates to the PromoIntelSourceUpdate builder.
func (_u *PromoIntelSourceUpdate) Where(ps ...predicate.PromoIntelSource) *PromoIntelSourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromoIntelSourceUpdate) SetUpdatedAt(v time.Time) *PromoIntelSourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PromoIntelSourceUpdate) SetName(v string) *PromoIntelSourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableName(v *string) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *PromoIntelSourceUpdate) SetVendor(v string) *PromoIntelSourceUpdate {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableVendor(v *string) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *PromoIntelSourceUpdate) SetCategory(v string) *PromoIntelSourceUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableCategory(v *string) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *PromoIntelSourceUpdate) SetURL(v string) *PromoIntelSourceUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableURL(v *string) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetFetchIntervalMinutes sets the "fetch_interval_minutes" field.
func (_u *PromoIntelSourceUpdate) SetFetchIntervalMinutes(v int) *PromoIntelSourceUpdate {
	_u.mutation.ResetFetchIntervalMinutes()
	_u.mutation.SetFetchIntervalMinutes(v)
	return _u
}

// SetNillableFetchIntervalMinutes sets the "fetch_interval_minutes" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableFetchIntervalMinutes(v *int) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetFetchIntervalMinutes(*v)
	}
	return _u
}

// AddFetchIntervalMinutes adds value to the "fetch_interval_minutes" field.
func (_u *PromoIntelSourceUpdate) AddFetchIntervalMinutes(v int) *PromoIntelSourceUpdate {
	_u.mutation.AddFetchIntervalMinutes(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PromoIntelSourceUpdate) SetEnabled(v bool) *PromoIntelSourceUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableEnabled(v *bool) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLlmExtract sets the "llm_extract" field.
func (_u *PromoIntelSourceUpdate) SetLlmExtract(v bool) *PromoIntelSourceUpdate {
	_u.mutation.SetLlmExtract(v)
	return _u
}

// SetNillableLlmExtract sets the "llm_extract" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableLlmExtract(v *bool) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetLlmExtract(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PromoIntelSourceUpdate) SetNotes(v string) *PromoIntelSourceUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableNotes(v *string) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (_u *PromoIntelSourceUpdate) SetLastFetchedAt(v time.Time) *PromoIntelSourceUpdate {
	_u.mutation.SetLastFetchedAt(v)
	return _u
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableLastFetchedAt(v *time.Time) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetLastFetchedAt(*v)
	}
	return _u
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (_u *PromoIntelSourceUpdate) ClearLastFetchedAt() *PromoIntelSourceUpdate {
	_u.mutation.ClearLastFetchedAt()
	return _u
}

// SetLastExtractedHash sets the "last_extracted_hash" field.
func (_u *PromoIntelSourceUpdate) SetLastExtractedHash(v string) *PromoIntelSourceUpdate {
	_u.mutation.SetLastExtractedHash(v)
	return _u
}

// SetNillableLastExtractedHash sets the "last_extracted_hash" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableLastExtractedHash(v *string) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetLastExtractedHash(*v)
	}
	return _u
}

// SetLastStatus sets the "last_status" field.
func (_u *PromoIntelSourceUpdate) SetLastStatus(v string) *PromoIntelSourceUpdate {
	_u.mutation.SetLastStatus(v)
	return _u
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableLastStatus(v *string) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetLastStatus(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *PromoIntelSourceUpdate) SetLastError(v string) *PromoIntelSourceUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableLastError(v *string) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PromoIntelSourceUpdate) SetCreatedBy(v int64) *PromoIntelSourceUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PromoIntelSourceUpdate) SetNillableCreatedBy(v *int64) *PromoIntelSourceUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PromoIntelSourceUpdate) AddCreatedBy(v int64) *PromoIntelSourceUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddItemIDs adds the "items" edge to the PromoIntelItem entity by IDs.
func (_u *PromoIntelSourceUpdate) AddItemIDs(ids ...int64) *PromoIntelSourceUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the PromoIntelItem entity.
func (_u *PromoIntelSourceUpdate) AddItems(v ...*PromoIntelItem) *PromoIntelSourceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the PromoIntelSourceMutation object of the builder.
func (_u *PromoIntelSourceUpdate) Mutation() *PromoIntelSourceMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the PromoIntelItem entity.
func (_u *PromoIntelSourceUpdate) ClearItems() *PromoIntelSourceUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to PromoIntelItem entities by IDs.
func (_u *PromoIntelSourceUpdate) RemoveItemIDs(ids ...int64) *PromoIntelSourceUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to PromoIntelItem entities.
func (_u *PromoIntelSourceUpdate) RemoveItems(v ...*PromoIntelItem) *PromoIntelSourceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromoIntelSourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromoIntelSourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromoIntelSourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromoIntelSourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromoIntelSourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promointelsource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromoIntelSourceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := promointelsource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vendor(); ok {
		if err := promointelsource.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := promointelsource.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := promointelsource.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FetchIntervalMinutes(); ok {
		if err := promointelsource.FetchIntervalMinutesValidator(v); err != nil {
			return &ValidationError{Name: "fetch_interval_minutes", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.fetch_interval_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastExtractedHash(); ok {
		if err := promointelsource.LastExtractedHashValidator(v); err != nil {
			return &ValidationError{Name: "last_extracted_hash", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.last_extracted_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastStatus(); ok {
		if err := promointelsource.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.last_status": %w`, err)}
		}
	}
	return nil
}

func (_u *PromoIntelSourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promointelsource.Table, promointelsource.Columns, sqlgraph.NewFieldSpec(promointelsource.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promointelsource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(promointelsource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(promointelsource.FieldVendor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(promointelsource.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(promointelsource.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.FetchIntervalMinutes(); ok {
		_spec.SetField(promointelsource.FieldFetchIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFetchIntervalMinutes(); ok {
		_spec.AddField(promointelsource.FieldFetchIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(promointelsource.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LlmExtract(); ok {
		_spec.SetField(promointelsource.FieldLlmExtract, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(promointelsource.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastFetchedAt(); ok {
		_spec.SetField(promointelsource.FieldLastFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.LastFetchedAtCleared() {
		_spec.ClearField(promointelsource.FieldLastFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastExtractedHash(); ok {
		_spec.SetField(promointelsource.FieldLastExtractedHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastStatus(); ok {
		_spec.SetField(promointelsource.FieldLastStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(promointelsource.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(promointelsource.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(promointelsource.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promointelsource.ItemsTable,
			Columns: []string{promointelsource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promointelsource.ItemsTable,
			Columns: []string{promointelsource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promointelsource.ItemsTable,
			Columns: []string{promointelsource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promointelsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromoIntelSourceUpdateOne is the builder for updating a single PromoIntelSource entity.
type PromoIntelSourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromoIntelSourceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromoIntelSourceUpdateOne) SetUpdatedAt(v time.Time) *PromoIntelSourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PromoIntelSourceUpdateOne) SetName(v string) *PromoIntelSourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableName(v *string) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *PromoIntelSourceUpdateOne) SetVendor(v string) *PromoIntelSourceUpdateOne {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableVendor(v *string) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *PromoIntelSourceUpdateOne) SetCategory(v string) *PromoIntelSourceUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableCategory(v *string) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *PromoIntelSourceUpdateOne) SetURL(v string) *PromoIntelSourceUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableURL(v *string) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetFetchIntervalMinutes sets the "fetch_interval_minutes" field.
func (_u *PromoIntelSourceUpdateOne) SetFetchIntervalMinutes(v int) *PromoIntelSourceUpdateOne {
	_u.mutation.ResetFetchIntervalMinutes()
	_u.mutation.SetFetchIntervalMinutes(v)
	return _u
}

// SetNillableFetchIntervalMinutes sets the "fetch_interval_minutes" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableFetchIntervalMinutes(v *int) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetFetchIntervalMinutes(*v)
	}
	return _u
}

// AddFetchIntervalMinutes adds value to the "fetch_interval_minutes" field.
func (_u *PromoIntelSourceUpdateOne) AddFetchIntervalMinutes(v int) *PromoIntelSourceUpdateOne {
	_u.mutation.AddFetchIntervalMinutes(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PromoIntelSourceUpdateOne) SetEnabled(v bool) *PromoIntelSourceUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableEnabled(v *bool) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLlmExtract sets the "llm_extract" field.
func (_u *PromoIntelSourceUpdateOne) SetLlmExtract(v bool) *PromoIntelSourceUpdateOne {
	_u.mutation.SetLlmExtract(v)
	return _u
}

// SetNillableLlmExtract sets the "llm_extract" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableLlmExtract(v *bool) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetLlmExtract(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PromoIntelSourceUpdateOne) SetNotes(v string) *PromoIntelSourceUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableNotes(v *string) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (_u *PromoIntelSourceUpdateOne) SetLastFetchedAt(v time.Time) *PromoIntelSourceUpdateOne {
	_u.mutation.SetLastFetchedAt(v)
	return _u
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableLastFetchedAt(v *time.Time) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetLastFetchedAt(*v)
	}
	return _u
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (_u *PromoIntelSourceUpdateOne) ClearLastFetchedAt() *PromoIntelSourceUpdateOne {
	_u.mutation.ClearLastFetchedAt()
	return _u
}

// SetLastExtractedHash sets the "last_extracted_hash" field.
func (_u *PromoIntelSourceUpdateOne) SetLastExtractedHash(v string) *PromoIntelSourceUpdateOne {
	_u.mutation.SetLastExtractedHash(v)
	return _u
}

// SetNillableLastExtractedHash sets the "last_extracted_hash" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableLastExtractedHash(v *string) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetLastExtractedHash(*v)
	}
	return _u
}

// SetLastStatus sets the "last_status" field.
func (_u *PromoIntelSourceUpdateOne) SetLastStatus(v string) *PromoIntelSourceUpdateOne {
	_u.mutation.SetLastStatus(v)
	return _u
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableLastStatus(v *string) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetLastStatus(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *PromoIntelSourceUpdateOne) SetLastError(v string) *PromoIntelSourceUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableLastError(v *string) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PromoIntelSourceUpdateOne) SetCreatedBy(v int64) *PromoIntelSourceUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PromoIntelSourceUpdateOne) SetNillableCreatedBy(v *int64) *PromoIntelSourceUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PromoIntelSourceUpdateOne) AddCreatedBy(v int64) *PromoIntelSourceUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddItemIDs adds the "items" edge to the PromoIntelItem entity by IDs.
func (_u *PromoIntelSourceUpdateOne) AddItemIDs(ids ...int64) *PromoIntelSourceUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the PromoIntelItem entity.
func (_u *PromoIntelSourceUpdateOne) AddItems(v ...*PromoIntelItem) *PromoIntelSourceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the PromoIntelSourceMutation object of the builder.
func (_u *PromoIntelSourceUpdateOne) Mutation() *PromoIntelSourceMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the PromoIntelItem entity.
func (_u *PromoIntelSourceUpdateOne) ClearItems() *PromoIntelSourceUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to PromoIntelItem entities by IDs.
func (_u *PromoIntelSourceUpdateOne) RemoveItemIDs(ids ...int64) *PromoIntelSourceUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to PromoIntelItem entities.
func (_u *PromoIntelSourceUpdateOne) RemoveItems(v ...*PromoIntelItem) *PromoIntelSourceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the PromoIntelSourceUpdate builder.
func (_u *PromoIntelSourceUpdateOne) Where(ps ...predicate.PromoIntelSource) *PromoIntelSourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromoIntelSourceUpdateOne) Select(field string, fields ...string) *PromoIntelSourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromoIntelSource entity.
func (_u *PromoIntelSourceUpdateOne) Save(ctx context.Context) (*PromoIntelSource, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromoIntelSourceUpdateOne) SaveX(ctx context.Context) *PromoIntelSource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromoIntelSourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromoIntelSourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromoIntelSourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promointelsource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromoIntelSourceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := promointelsource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vendor(); ok {
		if err := promointelsource.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := promointelsource.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := promointelsource.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FetchIntervalMinutes(); ok {
		if err := promointelsource.FetchIntervalMinutesValidator(v); err != nil {
			return &ValidationError{Name: "fetch_interval_minutes", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.fetch_interval_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastExtractedHash(); ok {
		if err := promointelsource.LastExtractedHashValidator(v); err != nil {
			return &ValidationError{Name: "last_extracted_hash", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.last_extracted_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastStatus(); ok {
		if err := promointelsource.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.last_status": %w`, err)}
		}
	}
	return nil
}

func (_u *PromoIntelSourceUpdateOne) sqlSave(ctx context.Context) (_node *PromoIntelSource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promointelsource.Table, promointelsource.Columns, sqlgraph.NewFieldSpec(promointelsource.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromoIntelSource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promointelsource.FieldID)
		for _, f := range fields {
			if !promointelsource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promointelsource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promointelsource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(promointelsource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(promointelsource.FieldVendor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(promointelsource.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(promointelsource.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.FetchIntervalMinutes(); ok {
		_spec.SetField(promointelsource.FieldFetchIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFetchIntervalMinutes(); ok {
		_spec.AddField(promointelsource.FieldFetchIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(promointelsource.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LlmExtract(); ok {
		_spec.SetField(promointelsource.FieldLlmExtract, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(promointelsource.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastFetchedAt(); ok {
		_spec.SetField(promointelsource.FieldLastFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.LastFetchedAtCleared() {
		_spec.ClearField(promointelsource.FieldLastFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastExtractedHash(); ok {
		_spec.SetField(promointelsource.FieldLastExtractedHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastStatus(); ok {
		_spec.SetField(promointelsource.FieldLastStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(promointelsource.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(promointelsource.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(promointelsource.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promointelsource.ItemsTable,
			Columns: []string{promointelsource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promointelsource.ItemsTable,
			Columns: []string{promointelsource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promointelsource.ItemsTable,
			Columns: []string{promointelsource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PromoIntelSource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promointelsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
