// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/promointelitem"
	"github.com/Wei-Shaw/sub2api/ent/promointelsource"
)

// PromoIntelItemUpdate is the builder for updating PromoIntelItem entities.
type PromoIntelItemUpdate struct {
	config
	hooks    []Hook
	mutation *PromoIntelItemMutation
}

// Where appends a list predicates to the PromoIntelItemUpdate builder.
func (_u *PromoIntelItemUpdate) Where(ps ...predicate.PromoIntelItem) *PromoIntelItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromoIntelItemUpdate) SetUpdatedAt(v time.Time) *PromoIntelItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *PromoIntelItemUpdate) SetSourceID(v int64) *PromoIntelItemUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableSourceID(v *int64) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *PromoIntelItemUpdate) SetVendor(v string) *PromoIntelItemUpdate {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableVendor(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *PromoIntelItemUpdate) SetCategory(v string) *PromoIntelItemUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableCategory(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PromoIntelItemUpdate) SetTitle(v string) *PromoIntelItemUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableTitle(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *PromoIntelItemUpdate) SetSummary(v string) *PromoIntelItemUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableSummary(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *PromoIntelItemUpdate) SetDetails(v string) *PromoIntelItemUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableDetails(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// SetDiscountInfo sets the "discount_info" field.
func (_u *PromoIntelItemUpdate) SetDiscountInfo(v string) *PromoIntelItemUpdate {
	_u.mutation.SetDiscountInfo(v)
	return _u
}

// SetNillableDiscountInfo sets the "discount_info" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableDiscountInfo(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetDiscountInfo(*v)
	}
	return _u
}

// SetValidUntil sets the "valid_until" field.
func (_u *PromoIntelItemUpdate) SetValidUntil(v string) *PromoIntelItemUpdate {
	_u.mutation.SetValidUntil(v)
	return _u
}

// SetNillableValidUntil sets the "valid_until" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableValidUntil(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetValidUntil(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *PromoIntelItemUpdate) SetURL(v string) *PromoIntelItemUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableURL(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetRelevance sets the "relevance" field.
func (_u *PromoIntelItemUpdate) SetRelevance(v string) *PromoIntelItemUpdate {
	_u.mutation.SetRelevance(v)
	return _u
}

// SetNillableRelevance sets the "relevance" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableRelevance(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetRelevance(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PromoIntelItemUpdate) SetStatus(v string) *PromoIntelItemUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableStatus(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *PromoIntelItemUpdate) SetFingerprint(v string) *PromoIntelItemUpdate {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableFingerprint(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetRawExcerpt sets the "raw_excerpt" field.
func (_u *PromoIntelItemUpdate) SetRawExcerpt(v string) *PromoIntelItemUpdate {
	_u.mutation.SetRawExcerpt(v)
	return _u
}

// SetNillableRawExcerpt sets the "raw_excerpt" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableRawExcerpt(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetRawExcerpt(*v)
	}
	return _u
}

// SetExtractStatus sets the "extract_status" field.
func (_u *PromoIntelItemUpdate) SetExtractStatus(v string) *PromoIntelItemUpdate {
	_u.mutation.SetExtractStatus(v)
	return _u
}

// SetNillableExtractStatus sets the "extract_status" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableExtractStatus(v *string) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetExtractStatus(*v)
	}
	return _u
}

// SetDigestDate sets the "digest_date" field.
func (_u *PromoIntelItemUpdate) SetDigestDate(v time.Time) *PromoIntelItemUpdate {
	_u.mutation.SetDigestDate(v)
	return _u
}

// SetNillableDigestDate sets the "digest_date" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableDigestDate(v *time.Time) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetDigestDate(*v)
	}
	return _u
}

// ClearDigestDate clears the value of the "digest_date" field.
func (_u *PromoIntelItemUpdate) ClearDigestDate() *PromoIntelItemUpdate {
	_u.mutation.ClearDigestDate()
	return _u
}

// SetSourceFetchedAt sets the "source_fetched_at" field.
func (_u *PromoIntelItemUpdate) SetSourceFetchedAt(v time.Time) *PromoIntelItemUpdate {
	_u.mutation.SetSourceFetchedAt(v)
	return _u
}

// SetNillableSourceFetchedAt sets the "source_fetched_at" field if the given value is not nil.
func (_u *PromoIntelItemUpdate) SetNillableSourceFetchedAt(v *time.Time) *PromoIntelItemUpdate {
	if v != nil {
		_u.SetSourceFetchedAt(*v)
	}
	return _u
}

// SetSource sets the "source" edge to the PromoIntelSource entity.
func (_u *PromoIntelItemUpdate) SetSource(v *PromoIntelSource) *PromoIntelItemUpdate {
	return _u.SetSourceID(v.ID)
}

// Mutation returns the PromoIntelItemMutation object of the builder.
func (_u *PromoIntelItemUpdate) Mutation() *PromoIntelItemMutation {
	return _u.mutation
}

// ClearSource clears the "source" edge to the PromoIntelSource entity.
func (_u *PromoIntelItemUpdate) ClearSource() *PromoIntelItemUpdate {
	_u.mutation.ClearSource()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromoIntelItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromoIntelItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromoIntelItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromoIntelItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromoIntelItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promointelitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromoIntelItemUpdate) check() error {
	if v, ok := _u.mutation.Vendor(); ok {
		if err := promointelitem.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := promointelitem.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relevance(); ok {
		if err := promointelitem.RelevanceValidator(v); err != nil {
			return &ValidationError{Name: "relevance", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.relevance": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := promointelitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fingerprint(); ok {
		if err := promointelitem.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExtractStatus(); ok {
		if err := promointelitem.ExtractStatusValidator(v); err != nil {
			return &ValidationError{Name: "extract_status", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.extract_status": %w`, err)}
		}
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromoIntelItem.source"`)
	}
	return nil
}

func (_u *PromoIntelItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promointelitem.Table, promointelitem.Columns, sqlgraph.NewFieldSpec(promointelitem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promointelitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(promointelitem.FieldVendor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(promointelitem.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(promointelitem.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(promointelitem.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(promointelitem.FieldDetails, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscountInfo(); ok {
		_spec.SetField(promointelitem.FieldDiscountInfo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidUntil(); ok {
		_spec.SetField(promointelitem.FieldValidUntil, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(promointelitem.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Relevance(); ok {
		_spec.SetField(promointelitem.FieldRelevance, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(promointelitem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(promointelitem.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawExcerpt(); ok {
		_spec.SetField(promointelitem.FieldRawExcerpt, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExtractStatus(); ok {
		_spec.SetField(promointelitem.FieldExtractStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DigestDate(); ok {
		_spec.SetField(promointelitem.FieldDigestDate, field.TypeTime, value)
	}
	if _u.mutation.DigestDateCleared() {
		_spec.ClearField(promointelitem.FieldDigestDate, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceFetchedAt(); ok {
		_spec.SetField(promointelitem.FieldSourceFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promointelitem.SourceTable,
			Columns: []string{promointelitem.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelsource.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promointelitem.SourceTable,
			Columns: []string{promointelitem.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelsource.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promointelitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromoIntelItemUpdateOne is the builder for updating a single PromoIntelItem entity.
type PromoIntelItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromoIntelItemMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromoIntelItemUpdateOne) SetUpdatedAt(v time.Time) *PromoIntelItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *PromoIntelItemUpdateOne) SetSourceID(v int64) *PromoIntelItemUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableSourceID(v *int64) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *PromoIntelItemUpdateOne) SetVendor(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableVendor(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *PromoIntelItemUpdateOne) SetCategory(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableCategory(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PromoIntelItemUpdateOne) SetTitle(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableTitle(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *PromoIntelItemUpdateOne) SetSummary(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableSummary(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *PromoIntelItemUpdateOne) SetDetails(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableDetails(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// SetDiscountInfo sets the "discount_info" field.
func (_u *PromoIntelItemUpdateOne) SetDiscountInfo(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetDiscountInfo(v)
	return _u
}

// SetNillableDiscountInfo sets the "discount_info" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableDiscountInfo(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetDiscountInfo(*v)
	}
	return _u
}

// SetValidUntil sets the "valid_until" field.
func (_u *PromoIntelItemUpdateOne) SetValidUntil(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetValidUntil(v)
	return _u
}

// SetNillableValidUntil sets the "valid_until" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableValidUntil(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetValidUntil(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *PromoIntelItemUpdateOne) SetURL(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableURL(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetRelevance sets the "relevance" field.
func (_u *PromoIntelItemUpdateOne) SetRelevance(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetRelevance(v)
	return _u
}

// SetNillableRelevance sets the "relevance" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableRelevance(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetRelevance(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PromoIntelItemUpdateOne) SetStatus(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableStatus(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *PromoIntelItemUpdateOne) SetFingerprint(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableFingerprint(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetRawExcerpt sets the "raw_excerpt" field.
func (_u *PromoIntelItemUpdateOne) SetRawExcerpt(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetRawExcerpt(v)
	return _u
}

// SetNillableRawExcerpt sets the "raw_excerpt" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableRawExcerpt(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetRawExcerpt(*v)
	}
	return _u
}

// SetExtractStatus sets the "extract_status" field.
func (_u *PromoIntelItemUpdateOne) SetExtractStatus(v string) *PromoIntelItemUpdateOne {
	_u.mutation.SetExtractStatus(v)
	return _u
}

// SetNillableExtractStatus sets the "extract_status" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableExtractStatus(v *string) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetExtractStatus(*v)
	}
	return _u
}

// SetDigestDate sets the "digest_date" field.
func (_u *PromoIntelItemUpdateOne) SetDigestDate(v time.Time) *PromoIntelItemUpdateOne {
	_u.mutation.SetDigestDate(v)
	return _u
}

// SetNillableDigestDate sets the "digest_date" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableDigestDate(v *time.Time) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetDigestDate(*v)
	}
	return _u
}

// ClearDigestDate clears the value of the "digest_date" field.
func (_u *PromoIntelItemUpdateOne) ClearDigestDate() *PromoIntelItemUpdateOne {
	_u.mutation.ClearDigestDate()
	return _u
}

// SetSourceFetchedAt sets the "source_fetched_at" field.
func (_u *PromoIntelItemUpdateOne) SetSourceFetchedAt(v time.Time) *PromoIntelItemUpdateOne {
	_u.mutation.SetSourceFetchedAt(v)
	return _u
}

// SetNillableSourceFetchedAt sets the "source_fetched_at" field if the given value is not nil.
func (_u *PromoIntelItemUpdateOne) SetNillableSourceFetchedAt(v *time.Time) *PromoIntelItemUpdateOne {
	if v != nil {
		_u.SetSourceFetchedAt(*v)
	}
	return _u
}

// SetSource sets the "source" edge to the PromoIntelSource entity.
func (_u *PromoIntelItemUpdateOne) SetSource(v *PromoIntelSource) *PromoIntelItemUpdateOne {
	return _u.SetSourceID(v.ID)
}

// Mutation returns the PromoIntelItemMutation object of the builder.
func (_u *PromoIntelItemUpdateOne) Mutation() *PromoIntelItemMutation {
	return _u.mutation
}

// ClearSource clears the "source" edge to the PromoIntelSource entity.
func (_u *PromoIntelItemUpdateOne) ClearSource() *PromoIntelItemUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// Where appends a list predicates to the PromoIntelItemUpdate builder.
func (_u *PromoIntelItemUpdateOne) Where(ps ...predicate.PromoIntelItem) *PromoIntelItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromoIntelItemUpdateOne) Select(field string, fields ...string) *PromoIntelItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromoIntelItem entity.
func (_u *PromoIntelItemUpdateOne) Save(ctx context.Context) (*PromoIntelItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromoIntelItemUpdateOne) SaveX(ctx context.Context) *PromoIntelItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromoIntelItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromoIntelItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromoIntelItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promointelitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromoIntelItemUpdateOne) check() error {
	if v, ok := _u.mutation.Vendor(); ok {
		if err := promointelitem.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := promointelitem.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relevance(); ok {
		if err := promointelitem.RelevanceValidator(v); err != nil {
			return &ValidationError{Name: "relevance", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.relevance": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := promointelitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fingerprint(); ok {
		if err := promointelitem.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExtractStatus(); ok {
		if err := promointelitem.ExtractStatusValidator(v); err != nil {
			return &ValidationError{Name: "extract_status", err: fmt.Errorf(`ent: validator failed for field "PromoIntelItem.extract_status": %w`, err)}
		}
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromoIntelItem.source"`)
	}
	return nil
}

func (_u *PromoIntelItemUpdateOne) sqlSave(ctx context.Context) (_node *PromoIntelItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promointelitem.Table, promointelitem.Columns, sqlgraph.NewFieldSpec(promointelitem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromoIntelItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promointelitem.FieldID)
		for _, f := range fields {
			if !promointelitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promointelitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promointelitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(promointelitem.FieldVendor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(promointelitem.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(promointelitem.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(promointelitem.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(promointelitem.FieldDetails, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscountInfo(); ok {
		_spec.SetField(promointelitem.FieldDiscountInfo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidUntil(); ok {
		_spec.SetField(promointelitem.FieldValidUntil, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(promointelitem.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Relevance(); ok {
		_spec.SetField(promointelitem.FieldRelevance, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(promointelitem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(promointelitem.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawExcerpt(); ok {
		_spec.SetField(promointelitem.FieldRawExcerpt, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExtractStatus(); ok {
		_spec.SetField(promointelitem.FieldExtractStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DigestDate(); ok {
		_spec.SetField(promointelitem.FieldDigestDate, field.TypeTime, value)
	}
	if _u.mutation.DigestDateCleared() {
		_spec.ClearField(promointelitem.FieldDigestDate, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceFetchedAt(); ok {
		_spec.SetField(promointelitem.FieldSourceFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promointelitem.SourceTable,
			Columns: []string{promointelitem.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelsource.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promointelitem.SourceTable,
			Columns: []string{promointelitem.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelsource.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PromoIntelItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promointelitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
