// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/promointelitem"
	"github.com/Wei-Shaw/sub2api/ent/promointelsource"
)

// PromoIntelItem is the model entity for the PromoIntelItem schema.
type PromoIntelItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID int64 `json:"source_id,omitempty"`
	// Vendor holds the value of the "vendor" field.
	Vendor string `json:"vendor,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Details holds the value of the "details" field.
	Details string `json:"details,omitempty"`
	// DiscountInfo holds the value of the "discount_info" field.
	DiscountInfo string `json:"discount_info,omitempty"`
	// ValidUntil holds the value of the "valid_until" field.
	ValidUntil string `json:"valid_until,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Relevance holds the value of the "relevance" field.
	Relevance string `json:"relevance,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint string `json:"fingerprint,omitempty"`
	// RawExcerpt holds the value of the "raw_excerpt" field.
	RawExcerpt string `json:"raw_excerpt,omitempty"`
	// ExtractStatus holds the value of the "extract_status" field.
	ExtractStatus string `json:"extract_status,omitempty"`
	// DigestDate holds the value of the "digest_date" field.
	DigestDate *time.Time `json:"digest_date,omitempty"`
	// SourceFetchedAt holds the value of the "source_fetched_at" field.
	SourceFetchedAt time.Time `json:"source_fetched_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PromoIntelItemQuery when eager-loading is set.
	Edges        PromoIntelItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PromoIntelItemEdges holds the relations/edges for other nodes in the graph.
type PromoIntelItemEdges struct {
	// Source holds the value of the source edge.
	Source *PromoIntelSource `json:"source,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SourceOrErr returns the Source value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PromoIntelItemEdges) SourceOrErr() (*PromoIntelSource, error) {
	if e.Source != nil {
		return e.Source, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: promointelsource.Label}
	}
	return nil, &NotLoadedError{edge: "source"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromoIntelItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promointelitem.FieldID, promointelitem.FieldSourceID:
			values[i] = new(sql.NullInt64)
		case promointelitem.FieldVendor, promointelitem.FieldCategory, promointelitem.FieldTitle, promointelitem.FieldSummary, promointelitem.FieldDetails, promointelitem.FieldDiscountInfo, promointelitem.FieldValidUntil, promointelitem.FieldURL, promointelitem.FieldRelevance, promointelitem.FieldStatus, promointelitem.FieldFingerprint, promointelitem.FieldRawExcerpt, promointelitem.FieldExtractStatus:
			values[i] = new(sql.NullString)
		case promointelitem.FieldCreatedAt, promointelitem.FieldUpdatedAt, promointelitem.FieldDigestDate, promointelitem.FieldSourceFetchedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromoIntelItem fields.
func (_m *PromoIntelItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promointelitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case promointelitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case promointelitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case promointelitem.FieldSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.Int64
			}
		case promointelitem.FieldVendor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vendor", values[i])
			} else if value.Valid {
				_m.Vendor = value.String
			}
		case promointelitem.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case promointelitem.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case promointelitem.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case promointelitem.FieldDetails:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value.Valid {
				_m.Details = value.String
			}
		case promointelitem.FieldDiscountInfo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discount_info", values[i])
			} else if value.Valid {
				_m.DiscountInfo = value.String
			}
		case promointelitem.FieldValidUntil:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field valid_until", values[i])
			} else if value.Valid {
				_m.ValidUntil = value.String
			}
		case promointelitem.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case promointelitem.FieldRelevance:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relevance", values[i])
			} else if value.Valid {
				_m.Relevance = value.String
			}
		case promointelitem.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case promointelitem.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = value.String
			}
		case promointelitem.FieldRawExcerpt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_excerpt", values[i])
			} else if value.Valid {
				_m.RawExcerpt = value.String
			}
		case promointelitem.FieldExtractStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extract_status", values[i])
			} else if value.Valid {
				_m.ExtractStatus = value.String
			}
		case promointelitem.FieldDigestDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field digest_date", values[i])
			} else if value.Valid {
				_m.DigestDate = new(time.Time)
				*_m.DigestDate = value.Time
			}
		case promointelitem.FieldSourceFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field source_fetched_at", values[i])
			} else if value.Valid {
				_m.SourceFetchedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromoIntelItem.
// This includes values selected through modifiers, order, etc.
func (_m *PromoIntelItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySource queries the "source" edge of the PromoIntelItem entity.
func (_m *PromoIntelItem) QuerySource() *PromoIntelSourceQuery {
	return NewPromoIntelItemClient(_m.config).QuerySource(_m)
}

// Update returns a builder for updating this PromoIntelItem.
// Note that you need to call PromoIntelItem.Unwrap() before calling this method if this PromoIntelItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromoIntelItem) Update() *PromoIntelItemUpdateOne {
	return NewPromoIntelItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromoIntelItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromoIntelItem) Unwrap() *PromoIntelItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromoIntelItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromoIntelItem) String() string {
	var builder strings.Builder
	builder.WriteString("PromoIntelItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceID))
	builder.WriteString(", ")
	builder.WriteString("vendor=")
	builder.WriteString(_m.Vendor)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(_m.Details)
	builder.WriteString(", ")
	builder.WriteString("discount_info=")
	builder.WriteString(_m.DiscountInfo)
	builder.WriteString(", ")
	builder.WriteString("valid_until=")
	builder.WriteString(_m.ValidUntil)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("relevance=")
	builder.WriteString(_m.Relevance)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(_m.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("raw_excerpt=")
	builder.WriteString(_m.RawExcerpt)
	builder.WriteString(", ")
	builder.WriteString("extract_status=")
	builder.WriteString(_m.ExtractStatus)
	builder.WriteString(", ")
	if v := _m.DigestDate; v != nil {
		builder.WriteString("digest_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("source_fetched_at=")
	builder.WriteString(_m.SourceFetchedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PromoIntelItems is a parsable slice of PromoIntelItem.
type PromoIntelItems []*PromoIntelItem
