// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promointelitem"
	"github.com/Wei-Shaw/sub2api/ent/promointelsource"
)

// PromoIntelSourceCreate is the builder for creating a PromoIntelSource entity.
type PromoIntelSourceCreate struct {
	config
	mutation *PromoIntelSourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromoIntelSourceCreate) SetCreatedAt(v time.Time) *PromoIntelSourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableCreatedAt(v *time.Time) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromoIntelSourceCreate) SetUpdatedAt(v time.Time) *PromoIntelSourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableUpdatedAt(v *time.Time) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PromoIntelSourceCreate) SetName(v string) *PromoIntelSourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetVendor sets the "vendor" field.
func (_c *PromoIntelSourceCreate) SetVendor(v string) *PromoIntelSourceCreate {
	_c.mutation.SetVendor(v)
	return _c
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableVendor(v *string) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetVendor(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *PromoIntelSourceCreate) SetCategory(v string) *PromoIntelSourceCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableCategory(v *string) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *PromoIntelSourceCreate) SetURL(v string) *PromoIntelSourceCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableURL(v *string) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetFetchIntervalMinutes sets the "fetch_interval_minutes" field.
func (_c *PromoIntelSourceCreate) SetFetchIntervalMinutes(v int) *PromoIntelSourceCreate {
	_c.mutation.SetFetchIntervalMinutes(v)
	return _c
}

// SetNillableFetchIntervalMinutes sets the "fetch_interval_minutes" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableFetchIntervalMinutes(v *int) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetFetchIntervalMinutes(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PromoIntelSourceCreate) SetEnabled(v bool) *PromoIntelSourceCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableEnabled(v *bool) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLlmExtract sets the "llm_extract" field.
func (_c *PromoIntelSourceCreate) SetLlmExtract(v bool) *PromoIntelSourceCreate {
	_c.mutation.SetLlmExtract(v)
	return _c
}

// SetNillableLlmExtract sets the "llm_extract" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableLlmExtract(v *bool) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetLlmExtract(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PromoIntelSourceCreate) SetNotes(v string) *PromoIntelSourceCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableNotes(v *string) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (_c *PromoIntelSourceCreate) SetLastFetchedAt(v time.Time) *PromoIntelSourceCreate {
	_c.mutation.SetLastFetchedAt(v)
	return _c
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableLastFetchedAt(v *time.Time) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetLastFetchedAt(*v)
	}
	return _c
}

// SetLastExtractedHash sets the "last_extracted_hash" field.
func (_c *PromoIntelSourceCreate) SetLastExtractedHash(v string) *PromoIntelSourceCreate {
	_c.mutation.SetLastExtractedHash(v)
	return _c
}

// SetNillableLastExtractedHash sets the "last_extracted_hash" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableLastExtractedHash(v *string) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetLastExtractedHash(*v)
	}
	return _c
}

// SetLastStatus sets the "last_status" field.
func (_c *PromoIntelSourceCreate) SetLastStatus(v string) *PromoIntelSourceCreate {
	_c.mutation.SetLastStatus(v)
	return _c
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableLastStatus(v *string) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetLastStatus(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *PromoIntelSourceCreate) SetLastError(v string) *PromoIntelSourceCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableLastError(v *string) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PromoIntelSourceCreate) SetCreatedBy(v int64) *PromoIntelSourceCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PromoIntelSourceCreate) SetNillableCreatedBy(v *int64) *PromoIntelSourceCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// AddItemIDs adds the "items" edge to the PromoIntelItem entity by IDs.
func (_c *PromoIntelSourceCreate) AddItemIDs(ids ...int64) *PromoIntelSourceCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the PromoIntelItem entity.
func (_c *PromoIntelSourceCreate) AddItems(v ...*PromoIntelItem) *PromoIntelSourceCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the PromoIntelSourceMutation object of the builder.
func (_c *PromoIntelSourceCreate) Mutation() *PromoIntelSourceMutation {
	return _c.mutation
}

// Save creates the PromoIntelSource in the database.
func (_c *PromoIntelSourceCreate) Save(ctx context.Context) (*PromoIntelSource, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromoIntelSourceCreate) SaveX(ctx context.Context) *PromoIntelSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromoIntelSourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromoIntelSourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromoIntelSourceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promointelsource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promointelsource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Vendor(); !ok {
		v := promointelsource.DefaultVendor
		_c.mutation.SetVendor(v)
	}
	if _, ok := _c.mutation.Category(); !ok {
		v := promointelsource.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.URL(); !ok {
		v := promointelsource.DefaultURL
		_c.mutation.SetURL(v)
	}
	if _, ok := _c.mutation.FetchIntervalMinutes(); !ok {
		v := promointelsource.DefaultFetchIntervalMinutes
		_c.mutation.SetFetchIntervalMinutes(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := promointelsource.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.LlmExtract(); !ok {
		v := promointelsource.DefaultLlmExtract
		_c.mutation.SetLlmExtract(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := promointelsource.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.LastExtractedHash(); !ok {
		v := promointelsource.DefaultLastExtractedHash
		_c.mutation.SetLastExtractedHash(v)
	}
	if _, ok := _c.mutation.LastStatus(); !ok {
		v := promointelsource.DefaultLastStatus
		_c.mutation.SetLastStatus(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := promointelsource.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := promointelsource.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromoIntelSourceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromoIntelSource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromoIntelSource.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PromoIntelSource.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := promointelsource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Vendor(); !ok {
		return &ValidationError{Name: "vendor", err: errors.New(`ent: missing required field "PromoIntelSource.vendor"`)}
	}
	if v, ok := _c.mutation.Vendor(); ok {
		if err := promointelsource.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.vendor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "PromoIntelSource.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := promointelsource.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "PromoIntelSource.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := promointelsource.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FetchIntervalMinutes(); !ok {
		return &ValidationError{Name: "fetch_interval_minutes", err: errors.New(`ent: missing required field "PromoIntelSource.fetch_interval_minutes"`)}
	}
	if v, ok := _c.mutation.FetchIntervalMinutes(); ok {
		if err := promointelsource.FetchIntervalMinutesValidator(v); err != nil {
			return &ValidationError{Name: "fetch_interval_minutes", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.fetch_interval_minutes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PromoIntelSource.enabled"`)}
	}
	if _, ok := _c.mutation.LlmExtract(); !ok {
		return &ValidationError{Name: "llm_extract", err: errors.New(`ent: missing required field "PromoIntelSource.llm_extract"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "PromoIntelSource.notes"`)}
	}
	if _, ok := _c.mutation.LastExtractedHash(); !ok {
		return &ValidationError{Name: "last_extracted_hash", err: errors.New(`ent: missing required field "PromoIntelSource.last_extracted_hash"`)}
	}
	if v, ok := _c.mutation.LastExtractedHash(); ok {
		if err := promointelsource.LastExtractedHashValidator(v); err != nil {
			return &ValidationError{Name: "last_extracted_hash", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.last_extracted_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastStatus(); !ok {
		return &ValidationError{Name: "last_status", err: errors.New(`ent: missing required field "PromoIntelSource.last_status"`)}
	}
	if v, ok := _c.mutation.LastStatus(); ok {
		if err := promointelsource.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "PromoIntelSource.last_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "PromoIntelSource.last_error"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "PromoIntelSource.created_by"`)}
	}
	return nil
}

func (_c *PromoIntelSourceCreate) sqlSave(ctx context.Context) (*PromoIntelSource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromoIntelSourceCreate) createSpec() (*PromoIntelSource, *sqlgraph.CreateSpec) {
	var (
		_node = &PromoIntelSource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promointelsource.Table, sqlgraph.NewFieldSpec(promointelsource.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promointelsource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promointelsource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(promointelsource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Vendor(); ok {
		_spec.SetField(promointelsource.FieldVendor, field.TypeString, value)
		_node.Vendor = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(promointelsource.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(promointelsource.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.FetchIntervalMinutes(); ok {
		_spec.SetField(promointelsource.FieldFetchIntervalMinutes, field.TypeInt, value)
		_node.FetchIntervalMinutes = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(promointelsource.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.LlmExtract(); ok {
		_spec.SetField(promointelsource.FieldLlmExtract, field.TypeBool, value)
		_node.LlmExtract = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(promointelsource.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.LastFetchedAt(); ok {
		_spec.SetField(promointelsource.FieldLastFetchedAt, field.TypeTime, value)
		_node.LastFetchedAt = &value
	}
	if value, ok := _c.mutation.LastExtractedHash(); ok {
		_spec.SetField(promointelsource.FieldLastExtractedHash, field.TypeString, value)
		_node.LastExtractedHash = value
	}
	if value, ok := _c.mutation.LastStatus(); ok {
		_spec.SetField(promointelsource.FieldLastStatus, field.TypeString, value)
		_node.LastStatus = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(promointelsource.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(promointelsource.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promointelsource.ItemsTable,
			Columns: []string{promointelsource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promointelitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromoIntelSource.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromoIntelSourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromoIntelSourceCreate) OnConflict(opts ...sql.ConflictOption) *PromoIntelSourceUpsertOne {
	_c.conflict = opts
	return &PromoIntelSourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromoIntelSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromoIntelSourceCreate) OnConflictColumns(columns ...string) *PromoIntelSourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromoIntelSourceUpsertOne{
		create: _c,
	}
}

type (
	// PromoIntelSourceUpsertOne is the builder for "upsert"-ing
	//  one PromoIntelSource node.
	PromoIntelSourceUpsertOne struct {
		create *PromoIntelSourceCreate
	}

	// PromoIntelSourceUpsert is the "OnConflict" setter.
	PromoIntelSourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PromoIntelSourceUpsert) SetUpdatedAt(v time.Time) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateUpdatedAt() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *PromoIntelSourceUpsert) SetName(v string) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateName() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldName)
	return u
}

// SetVendor sets the "vendor" field.
func (u *PromoIntelSourceUpsert) SetVendor(v string) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldVendor, v)
	return u
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateVendor() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldVendor)
	return u
}

// SetCategory sets the "category" field.
func (u *PromoIntelSourceUpsert) SetCategory(v string) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateCategory() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldCategory)
	return u
}

// SetURL sets the "url" field.
func (u *PromoIntelSourceUpsert) SetURL(v string) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateURL() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldURL)
	return u
}

// SetFetchIntervalMinutes sets the "fetch_interval_minutes" field.
func (u *PromoIntelSourceUpsert) SetFetchIntervalMinutes(v int) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldFetchIntervalMinutes, v)
	return u
}

// UpdateFetchIntervalMinutes sets the "fetch_interval_minutes" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateFetchIntervalMinutes() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldFetchIntervalMinutes)
	return u
}

// AddFetchIntervalMinutes adds v to the "fetch_interval_minutes" field.
func (u *PromoIntelSourceUpsert) AddFetchIntervalMinutes(v int) *PromoIntelSourceUpsert {
	u.Add(promointelsource.FieldFetchIntervalMinutes, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PromoIntelSourceUpsert) SetEnabled(v bool) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateEnabled() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldEnabled)
	return u
}

// SetLlmExtract sets the "llm_extract" field.
func (u *PromoIntelSourceUpsert) SetLlmExtract(v bool) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldLlmExtract, v)
	return u
}

// UpdateLlmExtract sets the "llm_extract" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateLlmExtract() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldLlmExtract)
	return u
}

// SetNotes sets the "notes" field.
func (u *PromoIntelSourceUpsert) SetNotes(v string) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateNotes() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldNotes)
	return u
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (u *PromoIntelSourceUpsert) SetLastFetchedAt(v time.Time) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldLastFetchedAt, v)
	return u
}

// UpdateLastFetchedAt sets the "last_fetched_at" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateLastFetchedAt() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldLastFetchedAt)
	return u
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (u *PromoIntelSourceUpsert) ClearLastFetchedAt() *PromoIntelSourceUpsert {
	u.SetNull(promointelsource.FieldLastFetchedAt)
	return u
}

// SetLastExtractedHash sets the "last_extracted_hash" field.
func (u *PromoIntelSourceUpsert) SetLastExtractedHash(v string) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldLastExtractedHash, v)
	return u
}

// UpdateLastExtractedHash sets the "last_extracted_hash" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateLastExtractedHash() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldLastExtractedHash)
	return u
}

// SetLastStatus sets the "last_status" field.
func (u *PromoIntelSourceUpsert) SetLastStatus(v string) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldLastStatus, v)
	return u
}

// UpdateLastStatus sets the "last_status" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateLastStatus() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldLastStatus)
	return u
}

// SetLastError sets the "last_error" field.
func (u *PromoIntelSourceUpsert) SetLastError(v string) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateLastError() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldLastError)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *PromoIntelSourceUpsert) SetCreatedBy(v int64) *PromoIntelSourceUpsert {
	u.Set(promointelsource.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PromoIntelSourceUpsert) UpdateCreatedBy() *PromoIntelSourceUpsert {
	u.SetExcluded(promointelsource.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PromoIntelSourceUpsert) AddCreatedBy(v int64) *PromoIntelSourceUpsert {
	u.Add(promointelsource.FieldCreatedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PromoIntelSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromoIntelSourceUpsertOne) UpdateNewValues() *PromoIntelSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promointelsource.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromoIntelSource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromoIntelSourceUpsertOne) Ignore() *PromoIntelSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromoIntelSourceUpsertOne) DoNothing() *PromoIntelSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromoIntelSourceCreate.OnConflict
// documentation for more info.
func (u *PromoIntelSourceUpsertOne) Update(set func(*PromoIntelSourceUpsert)) *PromoIntelSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromoIntelSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromoIntelSourceUpsertOne) SetUpdatedAt(v time.Time) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateUpdatedAt() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *PromoIntelSourceUpsertOne) SetName(v string) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateName() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateName()
	})
}

// SetVendor sets the "vendor" field.
func (u *PromoIntelSourceUpsertOne) SetVendor(v string) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetVendor(v)
	})
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateVendor() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateVendor()
	})
}

// SetCategory sets the "category" field.
func (u *PromoIntelSourceUpsertOne) SetCategory(v string) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateCategory() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateCategory()
	})
}

// SetURL sets the "url" field.
func (u *PromoIntelSourceUpsertOne) SetURL(v string) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateURL() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateURL()
	})
}

// SetFetchIntervalMinutes sets the "fetch_interval_minutes" field.
func (u *PromoIntelSourceUpsertOne) SetFetchIntervalMinutes(v int) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetFetchIntervalMinutes(v)
	})
}

// AddFetchIntervalMinutes adds v to the "fetch_interval_minutes" field.
func (u *PromoIntelSourceUpsertOne) AddFetchIntervalMinutes(v int) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.AddFetchIntervalMinutes(v)
	})
}

// UpdateFetchIntervalMinutes sets the "fetch_interval_minutes" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateFetchIntervalMinutes() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateFetchIntervalMinutes()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PromoIntelSourceUpsertOne) SetEnabled(v bool) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateEnabled() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateEnabled()
	})
}

// SetLlmExtract sets the "llm_extract" field.
func (u *PromoIntelSourceUpsertOne) SetLlmExtract(v bool) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetLlmExtract(v)
	})
}

// UpdateLlmExtract sets the "llm_extract" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateLlmExtract() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateLlmExtract()
	})
}

// SetNotes sets the "notes" field.
func (u *PromoIntelSourceUpsertOne) SetNotes(v string) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateNotes() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateNotes()
	})
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (u *PromoIntelSourceUpsertOne) SetLastFetchedAt(v time.Time) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetLastFetchedAt(v)
	})
}

// UpdateLastFetchedAt sets the "last_fetched_at" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateLastFetchedAt() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateLastFetchedAt()
	})
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (u *PromoIntelSourceUpsertOne) ClearLastFetchedAt() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.ClearLastFetchedAt()
	})
}

// SetLastExtractedHash sets the "last_extracted_hash" field.
func (u *PromoIntelSourceUpsertOne) SetLastExtractedHash(v string) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetLastExtractedHash(v)
	})
}

// UpdateLastExtractedHash sets the "last_extracted_hash" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateLastExtractedHash() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateLastExtractedHash()
	})
}

// SetLastStatus sets the "last_status" field.
func (u *PromoIntelSourceUpsertOne) SetLastStatus(v string) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetLastStatus(v)
	})
}

// UpdateLastStatus sets the "last_status" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateLastStatus() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateLastStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *PromoIntelSourceUpsertOne) SetLastError(v string) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateLastError() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateLastError()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *PromoIntelSourceUpsertOne) SetCreatedBy(v int64) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PromoIntelSourceUpsertOne) AddCreatedBy(v int64) *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertOne) UpdateCreatedBy() *PromoIntelSourceUpsertOne {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *PromoIntelSourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromoIntelSourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromoIntelSourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromoIntelSourceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromoIntelSourceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromoIntelSourceCreateBulk is the builder for creating many PromoIntelSource entities in bulk.
type PromoIntelSourceCreateBulk struct {
	config
	err      error
	builders []*PromoIntelSourceCreate
	conflict []sql.ConflictOption
}

// Save creates the PromoIntelSource entities in the database.
func (_c *PromoIntelSourceCreateBulk) Save(ctx context.Context) ([]*PromoIntelSource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromoIntelSource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromoIntelSourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromoIntelSourceCreateBulk) SaveX(ctx context.Context) []*PromoIntelSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromoIntelSourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromoIntelSourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromoIntelSource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromoIntelSourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromoIntelSourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromoIntelSourceUpsertBulk {
	_c.conflict = opts
	return &PromoIntelSourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromoIntelSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromoIntelSourceCreateBulk) OnConflictColumns(columns ...string) *PromoIntelSourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromoIntelSourceUpsertBulk{
		create: _c,
	}
}

// PromoIntelSourceUpsertBulk is the builder for "upsert"-ing
// a bulk of PromoIntelSource nodes.
type PromoIntelSourceUpsertBulk struct {
	create *PromoIntelSourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromoIntelSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromoIntelSourceUpsertBulk) UpdateNewValues() *PromoIntelSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promointelsource.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromoIntelSource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromoIntelSourceUpsertBulk) Ignore() *PromoIntelSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromoIntelSourceUpsertBulk) DoNothing() *PromoIntelSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromoIntelSourceCreateBulk.OnConflict
// documentation for more info.
func (u *PromoIntelSourceUpsertBulk) Update(set func(*PromoIntelSourceUpsert)) *PromoIntelSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromoIntelSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromoIntelSourceUpsertBulk) SetUpdatedAt(v time.Time) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateUpdatedAt() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *PromoIntelSourceUpsertBulk) SetName(v string) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateName() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateName()
	})
}

// SetVendor sets the "vendor" field.
func (u *PromoIntelSourceUpsertBulk) SetVendor(v string) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetVendor(v)
	})
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateVendor() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateVendor()
	})
}

// SetCategory sets the "category" field.
func (u *PromoIntelSourceUpsertBulk) SetCategory(v string) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateCategory() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateCategory()
	})
}

// SetURL sets the "url" field.
func (u *PromoIntelSourceUpsertBulk) SetURL(v string) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateURL() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateURL()
	})
}

// SetFetchIntervalMinutes sets the "fetch_interval_minutes" field.
func (u *PromoIntelSourceUpsertBulk) SetFetchIntervalMinutes(v int) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetFetchIntervalMinutes(v)
	})
}

// AddFetchIntervalMinutes adds v to the "fetch_interval_minutes" field.
func (u *PromoIntelSourceUpsertBulk) AddFetchIntervalMinutes(v int) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.AddFetchIntervalMinutes(v)
	})
}

// UpdateFetchIntervalMinutes sets the "fetch_interval_minutes" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateFetchIntervalMinutes() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateFetchIntervalMinutes()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PromoIntelSourceUpsertBulk) SetEnabled(v bool) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateEnabled() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateEnabled()
	})
}

// SetLlmExtract sets the "llm_extract" field.
func (u *PromoIntelSourceUpsertBulk) SetLlmExtract(v bool) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetLlmExtract(v)
	})
}

// UpdateLlmExtract sets the "llm_extract" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateLlmExtract() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateLlmExtract()
	})
}

// SetNotes sets the "notes" field.
func (u *PromoIntelSourceUpsertBulk) SetNotes(v string) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateNotes() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateNotes()
	})
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (u *PromoIntelSourceUpsertBulk) SetLastFetchedAt(v time.Time) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetLastFetchedAt(v)
	})
}

// UpdateLastFetchedAt sets the "last_fetched_at" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateLastFetchedAt() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateLastFetchedAt()
	})
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (u *PromoIntelSourceUpsertBulk) ClearLastFetchedAt() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.ClearLastFetchedAt()
	})
}

// SetLastExtractedHash sets the "last_extracted_hash" field.
func (u *PromoIntelSourceUpsertBulk) SetLastExtractedHash(v string) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetLastExtractedHash(v)
	})
}

// UpdateLastExtractedHash sets the "last_extracted_hash" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateLastExtractedHash() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateLastExtractedHash()
	})
}

// SetLastStatus sets the "last_status" field.
func (u *PromoIntelSourceUpsertBulk) SetLastStatus(v string) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetLastStatus(v)
	})
}

// UpdateLastStatus sets the "last_status" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateLastStatus() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateLastStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *PromoIntelSourceUpsertBulk) SetLastError(v string) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateLastError() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateLastError()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *PromoIntelSourceUpsertBulk) SetCreatedBy(v int64) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PromoIntelSourceUpsertBulk) AddCreatedBy(v int64) *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PromoIntelSourceUpsertBulk) UpdateCreatedBy() *PromoIntelSourceUpsertBulk {
	return u.Update(func(s *PromoIntelSourceUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *PromoIntelSourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromoIntelSourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromoIntelSourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromoIntelSourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
