// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodegroup"
)

// RedeemCodeGroupQuery is the builder for querying RedeemCodeGroup entities.
type RedeemCodeGroupQuery struct {
	config
	ctx            *QueryContext
	order          []redeemcodegroup.OrderOption
	inters         []Interceptor
	predicates     []predicate.RedeemCodeGroup
	withRedeemCode *RedeemCodeQuery
	withGroup      *GroupQuery
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RedeemCodeGroupQuery builder.
func (_q *RedeemCodeGroupQuery) Where(ps ...predicate.RedeemCodeGroup) *RedeemCodeGroupQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RedeemCodeGroupQuery) Limit(limit int) *RedeemCodeGroupQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RedeemCodeGroupQuery) Offset(offset int) *RedeemCodeGroupQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RedeemCodeGroupQuery) Unique(unique bool) *RedeemCodeGroupQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RedeemCodeGroupQuery) Order(o ...redeemcodegroup.OrderOption) *RedeemCodeGroupQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRedeemCode chains the current query on the "redeem_code" edge.
func (_q *RedeemCodeGroupQuery) QueryRedeemCode() *RedeemCodeQuery {
	query := (&RedeemCodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(redeemcodegroup.Table, redeemcodegroup.FieldID, selector),
			sqlgraph.To(redeemcode.Table, redeemcode.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, redeemcodegroup.RedeemCodeTable, redeemcodegroup.RedeemCodeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (_q *RedeemCodeGroupQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(redeemcodegroup.Table, redeemcodegroup.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, redeemcodegroup.GroupTable, redeemcodegroup.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RedeemCodeGroup entity from the query.
// Returns a *NotFoundError when no RedeemCodeGroup was found.
func (_q *RedeemCodeGroupQuery) First(ctx context.Context) (*RedeemCodeGroup, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{redeemcodegroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RedeemCodeGroupQuery) FirstX(ctx context.Context) *RedeemCodeGroup {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RedeemCodeGroup ID from the query.
// Returns a *NotFoundError when no RedeemCodeGroup ID was found.
func (_q *RedeemCodeGroupQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{redeemcodegroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RedeemCodeGroupQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RedeemCodeGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RedeemCodeGroup entity is found.
// Returns a *NotFoundError when no RedeemCodeGroup entities are found.
func (_q *RedeemCodeGroupQuery) Only(ctx context.Context) (*RedeemCodeGroup, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{redeemcodegroup.Label}
	default:
		return nil, &NotSingularError{redeemcodegroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RedeemCodeGroupQuery) OnlyX(ctx context.Context) *RedeemCodeGroup {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RedeemCodeGroup ID in the query.
// Returns a *NotSingularError when more than one RedeemCodeGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RedeemCodeGroupQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{redeemcodegroup.Label}
	default:
		err = &NotSingularError{redeemcodegroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RedeemCodeGroupQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RedeemCodeGroups.
func (_q *RedeemCodeGroupQuery) All(ctx context.Context) ([]*RedeemCodeGroup, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RedeemCodeGroup, *RedeemCodeGroupQuery]()
	return withInterceptors[[]*RedeemCodeGroup](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RedeemCodeGroupQuery) AllX(ctx context.Context) []*RedeemCodeGroup {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RedeemCodeGroup IDs.
func (_q *RedeemCodeGroupQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(redeemcodegroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RedeemCodeGroupQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RedeemCodeGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RedeemCodeGroupQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RedeemCodeGroupQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RedeemCodeGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RedeemCodeGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RedeemCodeGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RedeemCodeGroupQuery) Clone() *RedeemCodeGroupQuery {
	if _q == nil {
		return nil
	}
	return &RedeemCodeGroupQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]redeemcodegroup.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.RedeemCodeGroup{}, _q.predicates...),
		withRedeemCode: _q.withRedeemCode.Clone(),
		withGroup:      _q.withGroup.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRedeemCode tells the query-builder to eager-load the nodes that are connected to
// the "redeem_code" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RedeemCodeGroupQuery) WithRedeemCode(opts ...func(*RedeemCodeQuery)) *RedeemCodeGroupQuery {
	query := (&RedeemCodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRedeemCode = query
	return _q
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RedeemCodeGroupQuery) WithGroup(opts ...func(*GroupQuery)) *RedeemCodeGroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RedeemCodeID int64 `json:"redeem_code_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RedeemCodeGroup.Query().
//		GroupBy(redeemcodegroup.FieldRedeemCodeID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RedeemCodeGroupQuery) GroupBy(field string, fields ...string) *RedeemCodeGroupGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RedeemCodeGroupGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = redeemcodegroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RedeemCodeID int64 `json:"redeem_code_id,omitempty"`
//	}
//
//	client.RedeemCodeGroup.Query().
//		Select(redeemcodegroup.FieldRedeemCodeID).
//		Scan(ctx, &v)
func (_q *RedeemCodeGroupQuery) Select(fields ...string) *RedeemCodeGroupSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RedeemCodeGroupSelect{RedeemCodeGroupQuery: _q}
	sbuild.label = redeemcodegroup.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RedeemCodeGroupSelect configured with the given aggregations.
func (_q *RedeemCodeGroupQuery) Aggregate(fns ...AggregateFunc) *RedeemCodeGroupSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RedeemCodeGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !redeemcodegroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RedeemCodeGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RedeemCodeGroup, error) {
	var (
		nodes       = []*RedeemCodeGroup{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withRedeemCode != nil,
			_q.withGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RedeemCodeGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RedeemCodeGroup{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRedeemCode; query != nil {
		if err := _q.loadRedeemCode(ctx, query, nodes, nil,
			func(n *RedeemCodeGroup, e *RedeemCode) { n.Edges.RedeemCode = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *RedeemCodeGroup, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RedeemCodeGroupQuery) loadRedeemCode(ctx context.Context, query *RedeemCodeQuery, nodes []*RedeemCodeGroup, init func(*RedeemCodeGroup), assign func(*RedeemCodeGroup, *RedeemCode)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RedeemCodeGroup)
	for i := range nodes {
		fk := nodes[i].RedeemCodeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(redeemcode.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "redeem_code_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RedeemCodeGroupQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*RedeemCodeGroup, init func(*RedeemCodeGroup), assign func(*RedeemCodeGroup, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RedeemCodeGroup)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RedeemCodeGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RedeemCodeGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(redeemcodegroup.Table, redeemcodegroup.Columns, sqlgraph.NewFieldSpec(redeemcodegroup.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redeemcodegroup.FieldID)
		for i := range fields {
			if fields[i] != redeemcodegroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRedeemCode != nil {
			_spec.Node.AddColumnOnce(redeemcodegroup.FieldRedeemCodeID)
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(redeemcodegroup.FieldGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RedeemCodeGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(redeemcodegroup.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = redeemcodegroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RedeemCodeGroupQuery) ForUpdate(opts ...sql.LockOption) *RedeemCodeGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RedeemCodeGroupQuery) ForShare(opts ...sql.LockOption) *RedeemCodeGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// RedeemCodeGroupGroupBy is the group-by builder for RedeemCodeGroup entities.
type RedeemCodeGroupGroupBy struct {
	selector
	build *RedeemCodeGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RedeemCodeGroupGroupBy) Aggregate(fns ...AggregateFunc) *RedeemCodeGroupGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RedeemCodeGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RedeemCodeGroupQuery, *RedeemCodeGroupGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RedeemCodeGroupGroupBy) sqlScan(ctx context.Context, root *RedeemCodeGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RedeemCodeGroupSelect is the builder for selecting fields of RedeemCodeGroup entities.
type RedeemCodeGroupSelect struct {
	*RedeemCodeGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RedeemCodeGroupSelect) Aggregate(fns ...AggregateFunc) *RedeemCodeGroupSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RedeemCodeGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RedeemCodeGroupQuery, *RedeemCodeGroupSelect](ctx, _s.RedeemCodeGroupQuery, _s, _s.inters, v)
}

func (_s *RedeemCodeGroupSelect) sqlScan(ctx context.Context, root *RedeemCodeGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
