// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodegroup"
)

// RedeemCodeGroup is the model entity for the RedeemCodeGroup schema.
type RedeemCodeGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RedeemCodeID holds the value of the "redeem_code_id" field.
	RedeemCodeID int64 `json:"redeem_code_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// ValidityDays holds the value of the "validity_days" field.
	ValidityDays int `json:"validity_days,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RedeemCodeGroupQuery when eager-loading is set.
	Edges        RedeemCodeGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RedeemCodeGroupEdges holds the relations/edges for other nodes in the graph.
type RedeemCodeGroupEdges struct {
	// RedeemCode holds the value of the redeem_code edge.
	RedeemCode *RedeemCode `json:"redeem_code,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RedeemCodeOrErr returns the RedeemCode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RedeemCodeGroupEdges) RedeemCodeOrErr() (*RedeemCode, error) {
	if e.RedeemCode != nil {
		return e.RedeemCode, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: redeemcode.Label}
	}
	return nil, &NotLoadedError{edge: "redeem_code"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RedeemCodeGroupEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RedeemCodeGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case redeemcodegroup.FieldID, redeemcodegroup.FieldRedeemCodeID, redeemcodegroup.FieldGroupID, redeemcodegroup.FieldValidityDays:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RedeemCodeGroup fields.
func (_m *RedeemCodeGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case redeemcodegroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case redeemcodegroup.FieldRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_code_id", values[i])
			} else if value.Valid {
				_m.RedeemCodeID = value.Int64
			}
		case redeemcodegroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case redeemcodegroup.FieldValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validity_days", values[i])
			} else if value.Valid {
				_m.ValidityDays = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RedeemCodeGroup.
// This includes values selected through modifiers, order, etc.
func (_m *RedeemCodeGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRedeemCode queries the "redeem_code" edge of the RedeemCodeGroup entity.
func (_m *RedeemCodeGroup) QueryRedeemCode() *RedeemCodeQuery {
	return NewRedeemCodeGroupClient(_m.config).QueryRedeemCode(_m)
}

// QueryGroup queries the "group" edge of the RedeemCodeGroup entity.
func (_m *RedeemCodeGroup) QueryGroup() *GroupQuery {
	return NewRedeemCodeGroupClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this RedeemCodeGroup.
// Note that you need to call RedeemCodeGroup.Unwrap() before calling this method if this RedeemCodeGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RedeemCodeGroup) Update() *RedeemCodeGroupUpdateOne {
	return NewRedeemCodeGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RedeemCodeGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RedeemCodeGroup) Unwrap() *RedeemCodeGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RedeemCodeGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RedeemCodeGroup) String() string {
	var builder strings.Builder
	builder.WriteString("RedeemCodeGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("redeem_code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RedeemCodeID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("validity_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidityDays))
	builder.WriteByte(')')
	return builder.String()
}

// RedeemCodeGroups is a parsable slice of RedeemCodeGroup.
type RedeemCodeGroups []*RedeemCodeGroup
