// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodegroup"
)

// RedeemCodeGroupCreate is the builder for creating a RedeemCodeGroup entity.
type RedeemCodeGroupCreate struct {
	config
	mutation *RedeemCodeGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *RedeemCodeGroupCreate) SetRedeemCodeID(v int64) *RedeemCodeGroupCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *RedeemCodeGroupCreate) SetGroupID(v int64) *RedeemCodeGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *RedeemCodeGroupCreate) SetValidityDays(v int) *RedeemCodeGroupCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *RedeemCodeGroupCreate) SetNillableValidityDays(v *int) *RedeemCodeGroupCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_c *RedeemCodeGroupCreate) SetRedeemCode(v *RedeemCode) *RedeemCodeGroupCreate {
	return _c.SetRedeemCodeID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *RedeemCodeGroupCreate) SetGroup(v *Group) *RedeemCodeGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the RedeemCodeGroupMutation object of the builder.
func (_c *RedeemCodeGroupCreate) Mutation() *RedeemCodeGroupMutation {
	return _c.mutation
}

// Save creates the RedeemCodeGroup in the database.
func (_c *RedeemCodeGroupCreate) Save(ctx context.Context) (*RedeemCodeGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RedeemCodeGroupCreate) SaveX(ctx context.Context) *RedeemCodeGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCodeGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCodeGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RedeemCodeGroupCreate) defaults() {
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := redeemcodegroup.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RedeemCodeGroupCreate) check() error {
	if _, ok := _c.mutation.RedeemCodeID(); !ok {
		return &ValidationError{Name: "redeem_code_id", err: errors.New(`ent: missing required field "RedeemCodeGroup.redeem_code_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "RedeemCodeGroup.group_id"`)}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "RedeemCodeGroup.validity_days"`)}
	}
	if len(_c.mutation.RedeemCodeIDs()) == 0 {
		return &ValidationError{Name: "redeem_code", err: errors.New(`ent: missing required edge "RedeemCodeGroup.redeem_code"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "RedeemCodeGroup.group"`)}
	}
	return nil
}

func (_c *RedeemCodeGroupCreate) sqlSave(ctx context.Context) (*RedeemCodeGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RedeemCodeGroupCreate) createSpec() (*RedeemCodeGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &RedeemCodeGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(redeemcodegroup.Table, sqlgraph.NewFieldSpec(redeemcodegroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(redeemcodegroup.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if nodes := _c.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodegroup.RedeemCodeTable,
			Columns: []string{redeemcodegroup.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RedeemCodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodegroup.GroupTable,
			Columns: []string{redeemcodegroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCodeGroup.Create().
//		SetRedeemCodeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCodeGroupUpsert) {
//			SetRedeemCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCodeGroupCreate) OnConflict(opts ...sql.ConflictOption) *RedeemCodeGroupUpsertOne {
	_c.conflict = opts
	return &RedeemCodeGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCodeGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCodeGroupCreate) OnConflictColumns(columns ...string) *RedeemCodeGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCodeGroupUpsertOne{
		create: _c,
	}
}

type (
	// RedeemCodeGroupUpsertOne is the builder for "upsert"-ing
	//  one RedeemCodeGroup node.
	RedeemCodeGroupUpsertOne struct {
		create *RedeemCodeGroupCreate
	}

	// RedeemCodeGroupUpsert is the "OnConflict" setter.
	RedeemCodeGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeGroupUpsert) SetRedeemCodeID(v int64) *RedeemCodeGroupUpsert {
	u.Set(redeemcodegroup.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeGroupUpsert) UpdateRedeemCodeID() *RedeemCodeGroupUpsert {
	u.SetExcluded(redeemcodegroup.FieldRedeemCodeID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *RedeemCodeGroupUpsert) SetGroupID(v int64) *RedeemCodeGroupUpsert {
	u.Set(redeemcodegroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RedeemCodeGroupUpsert) UpdateGroupID() *RedeemCodeGroupUpsert {
	u.SetExcluded(redeemcodegroup.FieldGroupID)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *RedeemCodeGroupUpsert) SetValidityDays(v int) *RedeemCodeGroupUpsert {
	u.Set(redeemcodegroup.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *RedeemCodeGroupUpsert) UpdateValidityDays() *RedeemCodeGroupUpsert {
	u.SetExcluded(redeemcodegroup.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *RedeemCodeGroupUpsert) AddValidityDays(v int) *RedeemCodeGroupUpsert {
	u.Add(redeemcodegroup.FieldValidityDays, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RedeemCodeGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCodeGroupUpsertOne) UpdateNewValues() *RedeemCodeGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCodeGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RedeemCodeGroupUpsertOne) Ignore() *RedeemCodeGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCodeGroupUpsertOne) DoNothing() *RedeemCodeGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCodeGroupCreate.OnConflict
// documentation for more info.
func (u *RedeemCodeGroupUpsertOne) Update(set func(*RedeemCodeGroupUpsert)) *RedeemCodeGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCodeGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeGroupUpsertOne) SetRedeemCodeID(v int64) *RedeemCodeGroupUpsertOne {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeGroupUpsertOne) UpdateRedeemCodeID() *RedeemCodeGroupUpsertOne {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RedeemCodeGroupUpsertOne) SetGroupID(v int64) *RedeemCodeGroupUpsertOne {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RedeemCodeGroupUpsertOne) UpdateGroupID() *RedeemCodeGroupUpsertOne {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *RedeemCodeGroupUpsertOne) SetValidityDays(v int) *RedeemCodeGroupUpsertOne {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *RedeemCodeGroupUpsertOne) AddValidityDays(v int) *RedeemCodeGroupUpsertOne {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *RedeemCodeGroupUpsertOne) UpdateValidityDays() *RedeemCodeGroupUpsertOne {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.UpdateValidityDays()
	})
}

// Exec executes the query.
func (u *RedeemCodeGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCodeGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCodeGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RedeemCodeGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RedeemCodeGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RedeemCodeGroupCreateBulk is the builder for creating many RedeemCodeGroup entities in bulk.
type RedeemCodeGroupCreateBulk struct {
	config
	err      error
	builders []*RedeemCodeGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the RedeemCodeGroup entities in the database.
func (_c *RedeemCodeGroupCreateBulk) Save(ctx context.Context) ([]*RedeemCodeGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RedeemCodeGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RedeemCodeGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RedeemCodeGroupCreateBulk) SaveX(ctx context.Context) []*RedeemCodeGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCodeGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCodeGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCodeGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCodeGroupUpsert) {
//			SetRedeemCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCodeGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *RedeemCodeGroupUpsertBulk {
	_c.conflict = opts
	return &RedeemCodeGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCodeGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCodeGroupCreateBulk) OnConflictColumns(columns ...string) *RedeemCodeGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCodeGroupUpsertBulk{
		create: _c,
	}
}

// RedeemCodeGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of RedeemCodeGroup nodes.
type RedeemCodeGroupUpsertBulk struct {
	create *RedeemCodeGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RedeemCodeGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCodeGroupUpsertBulk) UpdateNewValues() *RedeemCodeGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCodeGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RedeemCodeGroupUpsertBulk) Ignore() *RedeemCodeGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCodeGroupUpsertBulk) DoNothing() *RedeemCodeGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCodeGroupCreateBulk.OnConflict
// documentation for more info.
func (u *RedeemCodeGroupUpsertBulk) Update(set func(*RedeemCodeGroupUpsert)) *RedeemCodeGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCodeGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeGroupUpsertBulk) SetRedeemCodeID(v int64) *RedeemCodeGroupUpsertBulk {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeGroupUpsertBulk) UpdateRedeemCodeID() *RedeemCodeGroupUpsertBulk {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RedeemCodeGroupUpsertBulk) SetGroupID(v int64) *RedeemCodeGroupUpsertBulk {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RedeemCodeGroupUpsertBulk) UpdateGroupID() *RedeemCodeGroupUpsertBulk {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *RedeemCodeGroupUpsertBulk) SetValidityDays(v int) *RedeemCodeGroupUpsertBulk {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *RedeemCodeGroupUpsertBulk) AddValidityDays(v int) *RedeemCodeGroupUpsertBulk {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *RedeemCodeGroupUpsertBulk) UpdateValidityDays() *RedeemCodeGroupUpsertBulk {
	return u.Update(func(s *RedeemCodeGroupUpsert) {
		s.UpdateValidityDays()
	})
}

// Exec executes the query.
func (u *RedeemCodeGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RedeemCodeGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCodeGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCodeGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
