// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeembatch"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/welfarebalance"
)

// RedeemBatchUpdate is the builder for updating RedeemBatch entities.
type RedeemBatchUpdate struct {
	config
	hooks    []Hook
	mutation *RedeemBatchMutation
}

// Where appends a list predicates to the RedeemBatchUpdate builder.
func (_u *RedeemBatchUpdate) Where(ps ...predicate.RedeemBatch) *RedeemBatchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RedeemBatchUpdate) SetName(v string) *RedeemBatchUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RedeemBatchUpdate) SetNillableName(v *string) *RedeemBatchUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *RedeemBatchUpdate) SetConfig(v map[string]interface{}) *RedeemBatchUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *RedeemBatchUpdate) ClearConfig() *RedeemBatchUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetCodeCount sets the "code_count" field.
func (_u *RedeemBatchUpdate) SetCodeCount(v int) *RedeemBatchUpdate {
	_u.mutation.ResetCodeCount()
	_u.mutation.SetCodeCount(v)
	return _u
}

// SetNillableCodeCount sets the "code_count" field if the given value is not nil.
func (_u *RedeemBatchUpdate) SetNillableCodeCount(v *int) *RedeemBatchUpdate {
	if v != nil {
		_u.SetCodeCount(*v)
	}
	return _u
}

// AddCodeCount adds value to the "code_count" field.
func (_u *RedeemBatchUpdate) AddCodeCount(v int) *RedeemBatchUpdate {
	_u.mutation.AddCodeCount(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RedeemBatchUpdate) SetCreatedBy(v int64) *RedeemBatchUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RedeemBatchUpdate) SetNillableCreatedBy(v *int64) *RedeemBatchUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *RedeemBatchUpdate) AddCreatedBy(v int64) *RedeemBatchUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_u *RedeemBatchUpdate) AddRedeemCodeIDs(ids ...int64) *RedeemBatchUpdate {
	_u.mutation.AddRedeemCodeIDs(ids...)
	return _u
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_u *RedeemBatchUpdate) AddRedeemCodes(v ...*RedeemCode) *RedeemBatchUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedeemCodeIDs(ids...)
}

// AddWelfareBalanceIDs adds the "welfare_balances" edge to the WelfareBalance entity by IDs.
func (_u *RedeemBatchUpdate) AddWelfareBalanceIDs(ids ...int64) *RedeemBatchUpdate {
	_u.mutation.AddWelfareBalanceIDs(ids...)
	return _u
}

// AddWelfareBalances adds the "welfare_balances" edges to the WelfareBalance entity.
func (_u *RedeemBatchUpdate) AddWelfareBalances(v ...*WelfareBalance) *RedeemBatchUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWelfareBalanceIDs(ids...)
}

// Mutation returns the RedeemBatchMutation object of the builder.
func (_u *RedeemBatchUpdate) Mutation() *RedeemBatchMutation {
	return _u.mutation
}

// ClearRedeemCodes clears all "redeem_codes" edges to the RedeemCode entity.
func (_u *RedeemBatchUpdate) ClearRedeemCodes() *RedeemBatchUpdate {
	_u.mutation.ClearRedeemCodes()
	return _u
}

// RemoveRedeemCodeIDs removes the "redeem_codes" edge to RedeemCode entities by IDs.
func (_u *RedeemBatchUpdate) RemoveRedeemCodeIDs(ids ...int64) *RedeemBatchUpdate {
	_u.mutation.RemoveRedeemCodeIDs(ids...)
	return _u
}

// RemoveRedeemCodes removes "redeem_codes" edges to RedeemCode entities.
func (_u *RedeemBatchUpdate) RemoveRedeemCodes(v ...*RedeemCode) *RedeemBatchUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedeemCodeIDs(ids...)
}

// ClearWelfareBalances clears all "welfare_balances" edges to the WelfareBalance entity.
func (_u *RedeemBatchUpdate) ClearWelfareBalances() *RedeemBatchUpdate {
	_u.mutation.ClearWelfareBalances()
	return _u
}

// RemoveWelfareBalanceIDs removes the "welfare_balances" edge to WelfareBalance entities by IDs.
func (_u *RedeemBatchUpdate) RemoveWelfareBalanceIDs(ids ...int64) *RedeemBatchUpdate {
	_u.mutation.RemoveWelfareBalanceIDs(ids...)
	return _u
}

// RemoveWelfareBalances removes "welfare_balances" edges to WelfareBalance entities.
func (_u *RedeemBatchUpdate) RemoveWelfareBalances(v ...*WelfareBalance) *RedeemBatchUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWelfareBalanceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RedeemBatchUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemBatchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RedeemBatchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemBatchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RedeemBatchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(redeembatch.Table, redeembatch.Columns, sqlgraph.NewFieldSpec(redeembatch.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(redeembatch.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(redeembatch.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(redeembatch.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.CodeCount(); ok {
		_spec.SetField(redeembatch.FieldCodeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCodeCount(); ok {
		_spec.AddField(redeembatch.FieldCodeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(redeembatch.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(redeembatch.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.RedeemCodesTable,
			Columns: []string{redeembatch.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedeemCodesIDs(); len(nodes) > 0 && !_u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.RedeemCodesTable,
			Columns: []string{redeembatch.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.RedeemCodesTable,
			Columns: []string{redeembatch.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WelfareBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.WelfareBalancesTable,
			Columns: []string{redeembatch.WelfareBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(welfarebalance.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWelfareBalancesIDs(); len(nodes) > 0 && !_u.mutation.WelfareBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.WelfareBalancesTable,
			Columns: []string{redeembatch.WelfareBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(welfarebalance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WelfareBalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.WelfareBalancesTable,
			Columns: []string{redeembatch.WelfareBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(welfarebalance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeembatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RedeemBatchUpdateOne is the builder for updating a single RedeemBatch entity.
type RedeemBatchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RedeemBatchMutation
}

// SetName sets the "name" field.
func (_u *RedeemBatchUpdateOne) SetName(v string) *RedeemBatchUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RedeemBatchUpdateOne) SetNillableName(v *string) *RedeemBatchUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *RedeemBatchUpdateOne) SetConfig(v map[string]interface{}) *RedeemBatchUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *RedeemBatchUpdateOne) ClearConfig() *RedeemBatchUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetCodeCount sets the "code_count" field.
func (_u *RedeemBatchUpdateOne) SetCodeCount(v int) *RedeemBatchUpdateOne {
	_u.mutation.ResetCodeCount()
	_u.mutation.SetCodeCount(v)
	return _u
}

// SetNillableCodeCount sets the "code_count" field if the given value is not nil.
func (_u *RedeemBatchUpdateOne) SetNillableCodeCount(v *int) *RedeemBatchUpdateOne {
	if v != nil {
		_u.SetCodeCount(*v)
	}
	return _u
}

// AddCodeCount adds value to the "code_count" field.
func (_u *RedeemBatchUpdateOne) AddCodeCount(v int) *RedeemBatchUpdateOne {
	_u.mutation.AddCodeCount(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RedeemBatchUpdateOne) SetCreatedBy(v int64) *RedeemBatchUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RedeemBatchUpdateOne) SetNillableCreatedBy(v *int64) *RedeemBatchUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *RedeemBatchUpdateOne) AddCreatedBy(v int64) *RedeemBatchUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_u *RedeemBatchUpdateOne) AddRedeemCodeIDs(ids ...int64) *RedeemBatchUpdateOne {
	_u.mutation.AddRedeemCodeIDs(ids...)
	return _u
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_u *RedeemBatchUpdateOne) AddRedeemCodes(v ...*RedeemCode) *RedeemBatchUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedeemCodeIDs(ids...)
}

// AddWelfareBalanceIDs adds the "welfare_balances" edge to the WelfareBalance entity by IDs.
func (_u *RedeemBatchUpdateOne) AddWelfareBalanceIDs(ids ...int64) *RedeemBatchUpdateOne {
	_u.mutation.AddWelfareBalanceIDs(ids...)
	return _u
}

// AddWelfareBalances adds the "welfare_balances" edges to the WelfareBalance entity.
func (_u *RedeemBatchUpdateOne) AddWelfareBalances(v ...*WelfareBalance) *RedeemBatchUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWelfareBalanceIDs(ids...)
}

// Mutation returns the RedeemBatchMutation object of the builder.
func (_u *RedeemBatchUpdateOne) Mutation() *RedeemBatchMutation {
	return _u.mutation
}

// ClearRedeemCodes clears all "redeem_codes" edges to the RedeemCode entity.
func (_u *RedeemBatchUpdateOne) ClearRedeemCodes() *RedeemBatchUpdateOne {
	_u.mutation.ClearRedeemCodes()
	return _u
}

// RemoveRedeemCodeIDs removes the "redeem_codes" edge to RedeemCode entities by IDs.
func (_u *RedeemBatchUpdateOne) RemoveRedeemCodeIDs(ids ...int64) *RedeemBatchUpdateOne {
	_u.mutation.RemoveRedeemCodeIDs(ids...)
	return _u
}

// RemoveRedeemCodes removes "redeem_codes" edges to RedeemCode entities.
func (_u *RedeemBatchUpdateOne) RemoveRedeemCodes(v ...*RedeemCode) *RedeemBatchUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedeemCodeIDs(ids...)
}

// ClearWelfareBalances clears all "welfare_balances" edges to the WelfareBalance entity.
func (_u *RedeemBatchUpdateOne) ClearWelfareBalances() *RedeemBatchUpdateOne {
	_u.mutation.ClearWelfareBalances()
	return _u
}

// RemoveWelfareBalanceIDs removes the "welfare_balances" edge to WelfareBalance entities by IDs.
func (_u *RedeemBatchUpdateOne) RemoveWelfareBalanceIDs(ids ...int64) *RedeemBatchUpdateOne {
	_u.mutation.RemoveWelfareBalanceIDs(ids...)
	return _u
}

// RemoveWelfareBalances removes "welfare_balances" edges to WelfareBalance entities.
func (_u *RedeemBatchUpdateOne) RemoveWelfareBalances(v ...*WelfareBalance) *RedeemBatchUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWelfareBalanceIDs(ids...)
}

// Where appends a list predicates to the RedeemBatchUpdate builder.
func (_u *RedeemBatchUpdateOne) Where(ps ...predicate.RedeemBatch) *RedeemBatchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RedeemBatchUpdateOne) Select(field string, fields ...string) *RedeemBatchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RedeemBatch entity.
func (_u *RedeemBatchUpdateOne) Save(ctx context.Context) (*RedeemBatch, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemBatchUpdateOne) SaveX(ctx context.Context) *RedeemBatch {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RedeemBatchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemBatchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RedeemBatchUpdateOne) sqlSave(ctx context.Context) (_node *RedeemBatch, err error) {
	_spec := sqlgraph.NewUpdateSpec(redeembatch.Table, redeembatch.Columns, sqlgraph.NewFieldSpec(redeembatch.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RedeemBatch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redeembatch.FieldID)
		for _, f := range fields {
			if !redeembatch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != redeembatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(redeembatch.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(redeembatch.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(redeembatch.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.CodeCount(); ok {
		_spec.SetField(redeembatch.FieldCodeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCodeCount(); ok {
		_spec.AddField(redeembatch.FieldCodeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(redeembatch.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(redeembatch.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.RedeemCodesTable,
			Columns: []string{redeembatch.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedeemCodesIDs(); len(nodes) > 0 && !_u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.RedeemCodesTable,
			Columns: []string{redeembatch.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.RedeemCodesTable,
			Columns: []string{redeembatch.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WelfareBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.WelfareBalancesTable,
			Columns: []string{redeembatch.WelfareBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(welfarebalance.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWelfareBalancesIDs(); len(nodes) > 0 && !_u.mutation.WelfareBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.WelfareBalancesTable,
			Columns: []string{redeembatch.WelfareBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(welfarebalance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WelfareBalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   redeembatch.WelfareBalancesTable,
			Columns: []string{redeembatch.WelfareBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(welfarebalance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RedeemBatch{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeembatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
