// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usageriskrollup"
)

// UsageRiskRollupUpdate is the builder for updating UsageRiskRollup entities.
type UsageRiskRollupUpdate struct {
	config
	hooks    []Hook
	mutation *UsageRiskRollupMutation
}

// Where appends a list predicates to the UsageRiskRollupUpdate builder.
func (_u *UsageRiskRollupUpdate) Where(ps ...predicate.UsageRiskRollup) *UsageRiskRollupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UsageRiskRollupUpdate) SetUserID(v int64) *UsageRiskRollupUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableUserID(v *int64) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UsageRiskRollupUpdate) AddUserID(v int64) *UsageRiskRollupUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UsageRiskRollupUpdate) SetGroupID(v int64) *UsageRiskRollupUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableGroupID(v *int64) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UsageRiskRollupUpdate) AddGroupID(v int64) *UsageRiskRollupUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetBucketHour sets the "bucket_hour" field.
func (_u *UsageRiskRollupUpdate) SetBucketHour(v time.Time) *UsageRiskRollupUpdate {
	_u.mutation.SetBucketHour(v)
	return _u
}

// SetNillableBucketHour sets the "bucket_hour" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableBucketHour(v *time.Time) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetBucketHour(*v)
	}
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *UsageRiskRollupUpdate) SetRequestCount(v int) *UsageRiskRollupUpdate {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableRequestCount(v *int) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *UsageRiskRollupUpdate) AddRequestCount(v int) *UsageRiskRollupUpdate {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetInputTokensSum sets the "input_tokens_sum" field.
func (_u *UsageRiskRollupUpdate) SetInputTokensSum(v int64) *UsageRiskRollupUpdate {
	_u.mutation.ResetInputTokensSum()
	_u.mutation.SetInputTokensSum(v)
	return _u
}

// SetNillableInputTokensSum sets the "input_tokens_sum" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableInputTokensSum(v *int64) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetInputTokensSum(*v)
	}
	return _u
}

// AddInputTokensSum adds value to the "input_tokens_sum" field.
func (_u *UsageRiskRollupUpdate) AddInputTokensSum(v int64) *UsageRiskRollupUpdate {
	_u.mutation.AddInputTokensSum(v)
	return _u
}

// SetOutputTokensSum sets the "output_tokens_sum" field.
func (_u *UsageRiskRollupUpdate) SetOutputTokensSum(v int64) *UsageRiskRollupUpdate {
	_u.mutation.ResetOutputTokensSum()
	_u.mutation.SetOutputTokensSum(v)
	return _u
}

// SetNillableOutputTokensSum sets the "output_tokens_sum" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableOutputTokensSum(v *int64) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetOutputTokensSum(*v)
	}
	return _u
}

// AddOutputTokensSum adds value to the "output_tokens_sum" field.
func (_u *UsageRiskRollupUpdate) AddOutputTokensSum(v int64) *UsageRiskRollupUpdate {
	_u.mutation.AddOutputTokensSum(v)
	return _u
}

// SetCacheReadTokensSum sets the "cache_read_tokens_sum" field.
func (_u *UsageRiskRollupUpdate) SetCacheReadTokensSum(v int64) *UsageRiskRollupUpdate {
	_u.mutation.ResetCacheReadTokensSum()
	_u.mutation.SetCacheReadTokensSum(v)
	return _u
}

// SetNillableCacheReadTokensSum sets the "cache_read_tokens_sum" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableCacheReadTokensSum(v *int64) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetCacheReadTokensSum(*v)
	}
	return _u
}

// AddCacheReadTokensSum adds value to the "cache_read_tokens_sum" field.
func (_u *UsageRiskRollupUpdate) AddCacheReadTokensSum(v int64) *UsageRiskRollupUpdate {
	_u.mutation.AddCacheReadTokensSum(v)
	return _u
}

// SetCostUsdSum sets the "cost_usd_sum" field.
func (_u *UsageRiskRollupUpdate) SetCostUsdSum(v float64) *UsageRiskRollupUpdate {
	_u.mutation.ResetCostUsdSum()
	_u.mutation.SetCostUsdSum(v)
	return _u
}

// SetNillableCostUsdSum sets the "cost_usd_sum" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableCostUsdSum(v *float64) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetCostUsdSum(*v)
	}
	return _u
}

// AddCostUsdSum adds value to the "cost_usd_sum" field.
func (_u *UsageRiskRollupUpdate) AddCostUsdSum(v float64) *UsageRiskRollupUpdate {
	_u.mutation.AddCostUsdSum(v)
	return _u
}

// SetOccupiedMsSum sets the "occupied_ms_sum" field.
func (_u *UsageRiskRollupUpdate) SetOccupiedMsSum(v int64) *UsageRiskRollupUpdate {
	_u.mutation.ResetOccupiedMsSum()
	_u.mutation.SetOccupiedMsSum(v)
	return _u
}

// SetNillableOccupiedMsSum sets the "occupied_ms_sum" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableOccupiedMsSum(v *int64) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetOccupiedMsSum(*v)
	}
	return _u
}

// AddOccupiedMsSum adds value to the "occupied_ms_sum" field.
func (_u *UsageRiskRollupUpdate) AddOccupiedMsSum(v int64) *UsageRiskRollupUpdate {
	_u.mutation.AddOccupiedMsSum(v)
	return _u
}

// SetNonWhitelistedUaCount sets the "non_whitelisted_ua_count" field.
func (_u *UsageRiskRollupUpdate) SetNonWhitelistedUaCount(v int) *UsageRiskRollupUpdate {
	_u.mutation.ResetNonWhitelistedUaCount()
	_u.mutation.SetNonWhitelistedUaCount(v)
	return _u
}

// SetNillableNonWhitelistedUaCount sets the "non_whitelisted_ua_count" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableNonWhitelistedUaCount(v *int) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetNonWhitelistedUaCount(*v)
	}
	return _u
}

// AddNonWhitelistedUaCount adds value to the "non_whitelisted_ua_count" field.
func (_u *UsageRiskRollupUpdate) AddNonWhitelistedUaCount(v int) *UsageRiskRollupUpdate {
	_u.mutation.AddNonWhitelistedUaCount(v)
	return _u
}

// SetComputedAt sets the "computed_at" field.
func (_u *UsageRiskRollupUpdate) SetComputedAt(v time.Time) *UsageRiskRollupUpdate {
	_u.mutation.SetComputedAt(v)
	return _u
}

// SetNillableComputedAt sets the "computed_at" field if the given value is not nil.
func (_u *UsageRiskRollupUpdate) SetNillableComputedAt(v *time.Time) *UsageRiskRollupUpdate {
	if v != nil {
		_u.SetComputedAt(*v)
	}
	return _u
}

// Mutation returns the UsageRiskRollupMutation object of the builder.
func (_u *UsageRiskRollupUpdate) Mutation() *UsageRiskRollupMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageRiskRollupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageRiskRollupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageRiskRollupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageRiskRollupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UsageRiskRollupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(usageriskrollup.Table, usageriskrollup.Columns, sqlgraph.NewFieldSpec(usageriskrollup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usageriskrollup.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usageriskrollup.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(usageriskrollup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(usageriskrollup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BucketHour(); ok {
		_spec.SetField(usageriskrollup.FieldBucketHour, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(usageriskrollup.FieldRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(usageriskrollup.FieldRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputTokensSum(); ok {
		_spec.SetField(usageriskrollup.FieldInputTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokensSum(); ok {
		_spec.AddField(usageriskrollup.FieldInputTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokensSum(); ok {
		_spec.SetField(usageriskrollup.FieldOutputTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokensSum(); ok {
		_spec.AddField(usageriskrollup.FieldOutputTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokensSum(); ok {
		_spec.SetField(usageriskrollup.FieldCacheReadTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokensSum(); ok {
		_spec.AddField(usageriskrollup.FieldCacheReadTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CostUsdSum(); ok {
		_spec.SetField(usageriskrollup.FieldCostUsdSum, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsdSum(); ok {
		_spec.AddField(usageriskrollup.FieldCostUsdSum, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OccupiedMsSum(); ok {
		_spec.SetField(usageriskrollup.FieldOccupiedMsSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOccupiedMsSum(); ok {
		_spec.AddField(usageriskrollup.FieldOccupiedMsSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.NonWhitelistedUaCount(); ok {
		_spec.SetField(usageriskrollup.FieldNonWhitelistedUaCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNonWhitelistedUaCount(); ok {
		_spec.AddField(usageriskrollup.FieldNonWhitelistedUaCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ComputedAt(); ok {
		_spec.SetField(usageriskrollup.FieldComputedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usageriskrollup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageRiskRollupUpdateOne is the builder for updating a single UsageRiskRollup entity.
type UsageRiskRollupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageRiskRollupMutation
}

// SetUserID sets the "user_id" field.
func (_u *UsageRiskRollupUpdateOne) SetUserID(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableUserID(v *int64) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UsageRiskRollupUpdateOne) AddUserID(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UsageRiskRollupUpdateOne) SetGroupID(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableGroupID(v *int64) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UsageRiskRollupUpdateOne) AddGroupID(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetBucketHour sets the "bucket_hour" field.
func (_u *UsageRiskRollupUpdateOne) SetBucketHour(v time.Time) *UsageRiskRollupUpdateOne {
	_u.mutation.SetBucketHour(v)
	return _u
}

// SetNillableBucketHour sets the "bucket_hour" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableBucketHour(v *time.Time) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetBucketHour(*v)
	}
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *UsageRiskRollupUpdateOne) SetRequestCount(v int) *UsageRiskRollupUpdateOne {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableRequestCount(v *int) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *UsageRiskRollupUpdateOne) AddRequestCount(v int) *UsageRiskRollupUpdateOne {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetInputTokensSum sets the "input_tokens_sum" field.
func (_u *UsageRiskRollupUpdateOne) SetInputTokensSum(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.ResetInputTokensSum()
	_u.mutation.SetInputTokensSum(v)
	return _u
}

// SetNillableInputTokensSum sets the "input_tokens_sum" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableInputTokensSum(v *int64) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetInputTokensSum(*v)
	}
	return _u
}

// AddInputTokensSum adds value to the "input_tokens_sum" field.
func (_u *UsageRiskRollupUpdateOne) AddInputTokensSum(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.AddInputTokensSum(v)
	return _u
}

// SetOutputTokensSum sets the "output_tokens_sum" field.
func (_u *UsageRiskRollupUpdateOne) SetOutputTokensSum(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.ResetOutputTokensSum()
	_u.mutation.SetOutputTokensSum(v)
	return _u
}

// SetNillableOutputTokensSum sets the "output_tokens_sum" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableOutputTokensSum(v *int64) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetOutputTokensSum(*v)
	}
	return _u
}

// AddOutputTokensSum adds value to the "output_tokens_sum" field.
func (_u *UsageRiskRollupUpdateOne) AddOutputTokensSum(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.AddOutputTokensSum(v)
	return _u
}

// SetCacheReadTokensSum sets the "cache_read_tokens_sum" field.
func (_u *UsageRiskRollupUpdateOne) SetCacheReadTokensSum(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.ResetCacheReadTokensSum()
	_u.mutation.SetCacheReadTokensSum(v)
	return _u
}

// SetNillableCacheReadTokensSum sets the "cache_read_tokens_sum" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableCacheReadTokensSum(v *int64) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetCacheReadTokensSum(*v)
	}
	return _u
}

// AddCacheReadTokensSum adds value to the "cache_read_tokens_sum" field.
func (_u *UsageRiskRollupUpdateOne) AddCacheReadTokensSum(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.AddCacheReadTokensSum(v)
	return _u
}

// SetCostUsdSum sets the "cost_usd_sum" field.
func (_u *UsageRiskRollupUpdateOne) SetCostUsdSum(v float64) *UsageRiskRollupUpdateOne {
	_u.mutation.ResetCostUsdSum()
	_u.mutation.SetCostUsdSum(v)
	return _u
}

// SetNillableCostUsdSum sets the "cost_usd_sum" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableCostUsdSum(v *float64) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetCostUsdSum(*v)
	}
	return _u
}

// AddCostUsdSum adds value to the "cost_usd_sum" field.
func (_u *UsageRiskRollupUpdateOne) AddCostUsdSum(v float64) *UsageRiskRollupUpdateOne {
	_u.mutation.AddCostUsdSum(v)
	return _u
}

// SetOccupiedMsSum sets the "occupied_ms_sum" field.
func (_u *UsageRiskRollupUpdateOne) SetOccupiedMsSum(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.ResetOccupiedMsSum()
	_u.mutation.SetOccupiedMsSum(v)
	return _u
}

// SetNillableOccupiedMsSum sets the "occupied_ms_sum" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableOccupiedMsSum(v *int64) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetOccupiedMsSum(*v)
	}
	return _u
}

// AddOccupiedMsSum adds value to the "occupied_ms_sum" field.
func (_u *UsageRiskRollupUpdateOne) AddOccupiedMsSum(v int64) *UsageRiskRollupUpdateOne {
	_u.mutation.AddOccupiedMsSum(v)
	return _u
}

// SetNonWhitelistedUaCount sets the "non_whitelisted_ua_count" field.
func (_u *UsageRiskRollupUpdateOne) SetNonWhitelistedUaCount(v int) *UsageRiskRollupUpdateOne {
	_u.mutation.ResetNonWhitelistedUaCount()
	_u.mutation.SetNonWhitelistedUaCount(v)
	return _u
}

// SetNillableNonWhitelistedUaCount sets the "non_whitelisted_ua_count" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableNonWhitelistedUaCount(v *int) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetNonWhitelistedUaCount(*v)
	}
	return _u
}

// AddNonWhitelistedUaCount adds value to the "non_whitelisted_ua_count" field.
func (_u *UsageRiskRollupUpdateOne) AddNonWhitelistedUaCount(v int) *UsageRiskRollupUpdateOne {
	_u.mutation.AddNonWhitelistedUaCount(v)
	return _u
}

// SetComputedAt sets the "computed_at" field.
func (_u *UsageRiskRollupUpdateOne) SetComputedAt(v time.Time) *UsageRiskRollupUpdateOne {
	_u.mutation.SetComputedAt(v)
	return _u
}

// SetNillableComputedAt sets the "computed_at" field if the given value is not nil.
func (_u *UsageRiskRollupUpdateOne) SetNillableComputedAt(v *time.Time) *UsageRiskRollupUpdateOne {
	if v != nil {
		_u.SetComputedAt(*v)
	}
	return _u
}

// Mutation returns the UsageRiskRollupMutation object of the builder.
func (_u *UsageRiskRollupUpdateOne) Mutation() *UsageRiskRollupMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsageRiskRollupUpdate builder.
func (_u *UsageRiskRollupUpdateOne) Where(ps ...predicate.UsageRiskRollup) *UsageRiskRollupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageRiskRollupUpdateOne) Select(field string, fields ...string) *UsageRiskRollupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageRiskRollup entity.
func (_u *UsageRiskRollupUpdateOne) Save(ctx context.Context) (*UsageRiskRollup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageRiskRollupUpdateOne) SaveX(ctx context.Context) *UsageRiskRollup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageRiskRollupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageRiskRollupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UsageRiskRollupUpdateOne) sqlSave(ctx context.Context) (_node *UsageRiskRollup, err error) {
	_spec := sqlgraph.NewUpdateSpec(usageriskrollup.Table, usageriskrollup.Columns, sqlgraph.NewFieldSpec(usageriskrollup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageRiskRollup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usageriskrollup.FieldID)
		for _, f := range fields {
			if !usageriskrollup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usageriskrollup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usageriskrollup.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usageriskrollup.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(usageriskrollup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(usageriskrollup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BucketHour(); ok {
		_spec.SetField(usageriskrollup.FieldBucketHour, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(usageriskrollup.FieldRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(usageriskrollup.FieldRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputTokensSum(); ok {
		_spec.SetField(usageriskrollup.FieldInputTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokensSum(); ok {
		_spec.AddField(usageriskrollup.FieldInputTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokensSum(); ok {
		_spec.SetField(usageriskrollup.FieldOutputTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokensSum(); ok {
		_spec.AddField(usageriskrollup.FieldOutputTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokensSum(); ok {
		_spec.SetField(usageriskrollup.FieldCacheReadTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokensSum(); ok {
		_spec.AddField(usageriskrollup.FieldCacheReadTokensSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CostUsdSum(); ok {
		_spec.SetField(usageriskrollup.FieldCostUsdSum, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsdSum(); ok {
		_spec.AddField(usageriskrollup.FieldCostUsdSum, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OccupiedMsSum(); ok {
		_spec.SetField(usageriskrollup.FieldOccupiedMsSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOccupiedMsSum(); ok {
		_spec.AddField(usageriskrollup.FieldOccupiedMsSum, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.NonWhitelistedUaCount(); ok {
		_spec.SetField(usageriskrollup.FieldNonWhitelistedUaCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNonWhitelistedUaCount(); ok {
		_spec.AddField(usageriskrollup.FieldNonWhitelistedUaCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ComputedAt(); ok {
		_spec.SetField(usageriskrollup.FieldComputedAt, field.TypeTime, value)
	}
	_node = &UsageRiskRollup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usageriskrollup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
