// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeembatch"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/welfarebalance"
)

// WelfareBalanceCreate is the builder for creating a WelfareBalance entity.
type WelfareBalanceCreate struct {
	config
	mutation *WelfareBalanceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *WelfareBalanceCreate) SetUserID(v int64) *WelfareBalanceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *WelfareBalanceCreate) SetRedeemCodeID(v int64) *WelfareBalanceCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetBatchID sets the "batch_id" field.
func (_c *WelfareBalanceCreate) SetBatchID(v int64) *WelfareBalanceCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetAmountInitial sets the "amount_initial" field.
func (_c *WelfareBalanceCreate) SetAmountInitial(v float64) *WelfareBalanceCreate {
	_c.mutation.SetAmountInitial(v)
	return _c
}

// SetNillableAmountInitial sets the "amount_initial" field if the given value is not nil.
func (_c *WelfareBalanceCreate) SetNillableAmountInitial(v *float64) *WelfareBalanceCreate {
	if v != nil {
		_c.SetAmountInitial(*v)
	}
	return _c
}

// SetAmountRemaining sets the "amount_remaining" field.
func (_c *WelfareBalanceCreate) SetAmountRemaining(v float64) *WelfareBalanceCreate {
	_c.mutation.SetAmountRemaining(v)
	return _c
}

// SetNillableAmountRemaining sets the "amount_remaining" field if the given value is not nil.
func (_c *WelfareBalanceCreate) SetNillableAmountRemaining(v *float64) *WelfareBalanceCreate {
	if v != nil {
		_c.SetAmountRemaining(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WelfareBalanceCreate) SetStatus(v string) *WelfareBalanceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WelfareBalanceCreate) SetNillableStatus(v *string) *WelfareBalanceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *WelfareBalanceCreate) SetExpiresAt(v time.Time) *WelfareBalanceCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WelfareBalanceCreate) SetCreatedAt(v time.Time) *WelfareBalanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WelfareBalanceCreate) SetNillableCreatedAt(v *time.Time) *WelfareBalanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WelfareBalanceCreate) SetUpdatedAt(v time.Time) *WelfareBalanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WelfareBalanceCreate) SetNillableUpdatedAt(v *time.Time) *WelfareBalanceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *WelfareBalanceCreate) SetUser(v *User) *WelfareBalanceCreate {
	return _c.SetUserID(v.ID)
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_c *WelfareBalanceCreate) SetRedeemCode(v *RedeemCode) *WelfareBalanceCreate {
	return _c.SetRedeemCodeID(v.ID)
}

// SetBatch sets the "batch" edge to the RedeemBatch entity.
func (_c *WelfareBalanceCreate) SetBatch(v *RedeemBatch) *WelfareBalanceCreate {
	return _c.SetBatchID(v.ID)
}

// Mutation returns the WelfareBalanceMutation object of the builder.
func (_c *WelfareBalanceCreate) Mutation() *WelfareBalanceMutation {
	return _c.mutation
}

// Save creates the WelfareBalance in the database.
func (_c *WelfareBalanceCreate) Save(ctx context.Context) (*WelfareBalance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WelfareBalanceCreate) SaveX(ctx context.Context) *WelfareBalance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WelfareBalanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WelfareBalanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WelfareBalanceCreate) defaults() {
	if _, ok := _c.mutation.AmountInitial(); !ok {
		v := welfarebalance.DefaultAmountInitial
		_c.mutation.SetAmountInitial(v)
	}
	if _, ok := _c.mutation.AmountRemaining(); !ok {
		v := welfarebalance.DefaultAmountRemaining
		_c.mutation.SetAmountRemaining(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := welfarebalance.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := welfarebalance.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := welfarebalance.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WelfareBalanceCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WelfareBalance.user_id"`)}
	}
	if _, ok := _c.mutation.RedeemCodeID(); !ok {
		return &ValidationError{Name: "redeem_code_id", err: errors.New(`ent: missing required field "WelfareBalance.redeem_code_id"`)}
	}
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "WelfareBalance.batch_id"`)}
	}
	if _, ok := _c.mutation.AmountInitial(); !ok {
		return &ValidationError{Name: "amount_initial", err: errors.New(`ent: missing required field "WelfareBalance.amount_initial"`)}
	}
	if _, ok := _c.mutation.AmountRemaining(); !ok {
		return &ValidationError{Name: "amount_remaining", err: errors.New(`ent: missing required field "WelfareBalance.amount_remaining"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WelfareBalance.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := welfarebalance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WelfareBalance.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "WelfareBalance.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WelfareBalance.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WelfareBalance.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "WelfareBalance.user"`)}
	}
	if len(_c.mutation.RedeemCodeIDs()) == 0 {
		return &ValidationError{Name: "redeem_code", err: errors.New(`ent: missing required edge "WelfareBalance.redeem_code"`)}
	}
	if len(_c.mutation.BatchIDs()) == 0 {
		return &ValidationError{Name: "batch", err: errors.New(`ent: missing required edge "WelfareBalance.batch"`)}
	}
	return nil
}

func (_c *WelfareBalanceCreate) sqlSave(ctx context.Context) (*WelfareBalance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WelfareBalanceCreate) createSpec() (*WelfareBalance, *sqlgraph.CreateSpec) {
	var (
		_node = &WelfareBalance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(welfarebalance.Table, sqlgraph.NewFieldSpec(welfarebalance.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AmountInitial(); ok {
		_spec.SetField(welfarebalance.FieldAmountInitial, field.TypeFloat64, value)
		_node.AmountInitial = value
	}
	if value, ok := _c.mutation.AmountRemaining(); ok {
		_spec.SetField(welfarebalance.FieldAmountRemaining, field.TypeFloat64, value)
		_node.AmountRemaining = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(welfarebalance.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(welfarebalance.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(welfarebalance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(welfarebalance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   welfarebalance.UserTable,
			Columns: []string{welfarebalance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   welfarebalance.RedeemCodeTable,
			Columns: []string{welfarebalance.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RedeemCodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   welfarebalance.BatchTable,
			Columns: []string{welfarebalance.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeembatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BatchID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WelfareBalance.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WelfareBalanceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *WelfareBalanceCreate) OnConflict(opts ...sql.ConflictOption) *WelfareBalanceUpsertOne {
	_c.conflict = opts
	return &WelfareBalanceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WelfareBalance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WelfareBalanceCreate) OnConflictColumns(columns ...string) *WelfareBalanceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WelfareBalanceUpsertOne{
		create: _c,
	}
}

type (
	// WelfareBalanceUpsertOne is the builder for "upsert"-ing
	//  one WelfareBalance node.
	WelfareBalanceUpsertOne struct {
		create *WelfareBalanceCreate
	}

	// WelfareBalanceUpsert is the "OnConflict" setter.
	WelfareBalanceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *WelfareBalanceUpsert) SetUserID(v int64) *WelfareBalanceUpsert {
	u.Set(welfarebalance.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WelfareBalanceUpsert) UpdateUserID() *WelfareBalanceUpsert {
	u.SetExcluded(welfarebalance.FieldUserID)
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *WelfareBalanceUpsert) SetRedeemCodeID(v int64) *WelfareBalanceUpsert {
	u.Set(welfarebalance.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *WelfareBalanceUpsert) UpdateRedeemCodeID() *WelfareBalanceUpsert {
	u.SetExcluded(welfarebalance.FieldRedeemCodeID)
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *WelfareBalanceUpsert) SetBatchID(v int64) *WelfareBalanceUpsert {
	u.Set(welfarebalance.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *WelfareBalanceUpsert) UpdateBatchID() *WelfareBalanceUpsert {
	u.SetExcluded(welfarebalance.FieldBatchID)
	return u
}

// SetAmountInitial sets the "amount_initial" field.
func (u *WelfareBalanceUpsert) SetAmountInitial(v float64) *WelfareBalanceUpsert {
	u.Set(welfarebalance.FieldAmountInitial, v)
	return u
}

// UpdateAmountInitial sets the "amount_initial" field to the value that was provided on create.
func (u *WelfareBalanceUpsert) UpdateAmountInitial() *WelfareBalanceUpsert {
	u.SetExcluded(welfarebalance.FieldAmountInitial)
	return u
}

// AddAmountInitial adds v to the "amount_initial" field.
func (u *WelfareBalanceUpsert) AddAmountInitial(v float64) *WelfareBalanceUpsert {
	u.Add(welfarebalance.FieldAmountInitial, v)
	return u
}

// SetAmountRemaining sets the "amount_remaining" field.
func (u *WelfareBalanceUpsert) SetAmountRemaining(v float64) *WelfareBalanceUpsert {
	u.Set(welfarebalance.FieldAmountRemaining, v)
	return u
}

// UpdateAmountRemaining sets the "amount_remaining" field to the value that was provided on create.
func (u *WelfareBalanceUpsert) UpdateAmountRemaining() *WelfareBalanceUpsert {
	u.SetExcluded(welfarebalance.FieldAmountRemaining)
	return u
}

// AddAmountRemaining adds v to the "amount_remaining" field.
func (u *WelfareBalanceUpsert) AddAmountRemaining(v float64) *WelfareBalanceUpsert {
	u.Add(welfarebalance.FieldAmountRemaining, v)
	return u
}

// SetStatus sets the "status" field.
func (u *WelfareBalanceUpsert) SetStatus(v string) *WelfareBalanceUpsert {
	u.Set(welfarebalance.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WelfareBalanceUpsert) UpdateStatus() *WelfareBalanceUpsert {
	u.SetExcluded(welfarebalance.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *WelfareBalanceUpsert) SetExpiresAt(v time.Time) *WelfareBalanceUpsert {
	u.Set(welfarebalance.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *WelfareBalanceUpsert) UpdateExpiresAt() *WelfareBalanceUpsert {
	u.SetExcluded(welfarebalance.FieldExpiresAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WelfareBalanceUpsert) SetUpdatedAt(v time.Time) *WelfareBalanceUpsert {
	u.Set(welfarebalance.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WelfareBalanceUpsert) UpdateUpdatedAt() *WelfareBalanceUpsert {
	u.SetExcluded(welfarebalance.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WelfareBalance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WelfareBalanceUpsertOne) UpdateNewValues() *WelfareBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(welfarebalance.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WelfareBalance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WelfareBalanceUpsertOne) Ignore() *WelfareBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WelfareBalanceUpsertOne) DoNothing() *WelfareBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WelfareBalanceCreate.OnConflict
// documentation for more info.
func (u *WelfareBalanceUpsertOne) Update(set func(*WelfareBalanceUpsert)) *WelfareBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WelfareBalanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *WelfareBalanceUpsertOne) SetUserID(v int64) *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WelfareBalanceUpsertOne) UpdateUserID() *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateUserID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *WelfareBalanceUpsertOne) SetRedeemCodeID(v int64) *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *WelfareBalanceUpsertOne) UpdateRedeemCodeID() *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetBatchID sets the "batch_id" field.
func (u *WelfareBalanceUpsertOne) SetBatchID(v int64) *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *WelfareBalanceUpsertOne) UpdateBatchID() *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateBatchID()
	})
}

// SetAmountInitial sets the "amount_initial" field.
func (u *WelfareBalanceUpsertOne) SetAmountInitial(v float64) *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetAmountInitial(v)
	})
}

// AddAmountInitial adds v to the "amount_initial" field.
func (u *WelfareBalanceUpsertOne) AddAmountInitial(v float64) *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.AddAmountInitial(v)
	})
}

// UpdateAmountInitial sets the "amount_initial" field to the value that was provided on create.
func (u *WelfareBalanceUpsertOne) UpdateAmountInitial() *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateAmountInitial()
	})
}

// SetAmountRemaining sets the "amount_remaining" field.
func (u *WelfareBalanceUpsertOne) SetAmountRemaining(v float64) *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetAmountRemaining(v)
	})
}

// AddAmountRemaining adds v to the "amount_remaining" field.
func (u *WelfareBalanceUpsertOne) AddAmountRemaining(v float64) *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.AddAmountRemaining(v)
	})
}

// UpdateAmountRemaining sets the "amount_remaining" field to the value that was provided on create.
func (u *WelfareBalanceUpsertOne) UpdateAmountRemaining() *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateAmountRemaining()
	})
}

// SetStatus sets the "status" field.
func (u *WelfareBalanceUpsertOne) SetStatus(v string) *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WelfareBalanceUpsertOne) UpdateStatus() *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *WelfareBalanceUpsertOne) SetExpiresAt(v time.Time) *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *WelfareBalanceUpsertOne) UpdateExpiresAt() *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WelfareBalanceUpsertOne) SetUpdatedAt(v time.Time) *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WelfareBalanceUpsertOne) UpdateUpdatedAt() *WelfareBalanceUpsertOne {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WelfareBalanceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WelfareBalanceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WelfareBalanceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WelfareBalanceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WelfareBalanceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WelfareBalanceCreateBulk is the builder for creating many WelfareBalance entities in bulk.
type WelfareBalanceCreateBulk struct {
	config
	err      error
	builders []*WelfareBalanceCreate
	conflict []sql.ConflictOption
}

// Save creates the WelfareBalance entities in the database.
func (_c *WelfareBalanceCreateBulk) Save(ctx context.Context) ([]*WelfareBalance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WelfareBalance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WelfareBalanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WelfareBalanceCreateBulk) SaveX(ctx context.Context) []*WelfareBalance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WelfareBalanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WelfareBalanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WelfareBalance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WelfareBalanceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *WelfareBalanceCreateBulk) OnConflict(opts ...sql.ConflictOption) *WelfareBalanceUpsertBulk {
	_c.conflict = opts
	return &WelfareBalanceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WelfareBalance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WelfareBalanceCreateBulk) OnConflictColumns(columns ...string) *WelfareBalanceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WelfareBalanceUpsertBulk{
		create: _c,
	}
}

// WelfareBalanceUpsertBulk is the builder for "upsert"-ing
// a bulk of WelfareBalance nodes.
type WelfareBalanceUpsertBulk struct {
	create *WelfareBalanceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WelfareBalance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WelfareBalanceUpsertBulk) UpdateNewValues() *WelfareBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(welfarebalance.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WelfareBalance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WelfareBalanceUpsertBulk) Ignore() *WelfareBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WelfareBalanceUpsertBulk) DoNothing() *WelfareBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WelfareBalanceCreateBulk.OnConflict
// documentation for more info.
func (u *WelfareBalanceUpsertBulk) Update(set func(*WelfareBalanceUpsert)) *WelfareBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WelfareBalanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *WelfareBalanceUpsertBulk) SetUserID(v int64) *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WelfareBalanceUpsertBulk) UpdateUserID() *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateUserID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *WelfareBalanceUpsertBulk) SetRedeemCodeID(v int64) *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *WelfareBalanceUpsertBulk) UpdateRedeemCodeID() *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetBatchID sets the "batch_id" field.
func (u *WelfareBalanceUpsertBulk) SetBatchID(v int64) *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *WelfareBalanceUpsertBulk) UpdateBatchID() *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateBatchID()
	})
}

// SetAmountInitial sets the "amount_initial" field.
func (u *WelfareBalanceUpsertBulk) SetAmountInitial(v float64) *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetAmountInitial(v)
	})
}

// AddAmountInitial adds v to the "amount_initial" field.
func (u *WelfareBalanceUpsertBulk) AddAmountInitial(v float64) *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.AddAmountInitial(v)
	})
}

// UpdateAmountInitial sets the "amount_initial" field to the value that was provided on create.
func (u *WelfareBalanceUpsertBulk) UpdateAmountInitial() *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateAmountInitial()
	})
}

// SetAmountRemaining sets the "amount_remaining" field.
func (u *WelfareBalanceUpsertBulk) SetAmountRemaining(v float64) *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetAmountRemaining(v)
	})
}

// AddAmountRemaining adds v to the "amount_remaining" field.
func (u *WelfareBalanceUpsertBulk) AddAmountRemaining(v float64) *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.AddAmountRemaining(v)
	})
}

// UpdateAmountRemaining sets the "amount_remaining" field to the value that was provided on create.
func (u *WelfareBalanceUpsertBulk) UpdateAmountRemaining() *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateAmountRemaining()
	})
}

// SetStatus sets the "status" field.
func (u *WelfareBalanceUpsertBulk) SetStatus(v string) *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WelfareBalanceUpsertBulk) UpdateStatus() *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *WelfareBalanceUpsertBulk) SetExpiresAt(v time.Time) *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *WelfareBalanceUpsertBulk) UpdateExpiresAt() *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WelfareBalanceUpsertBulk) SetUpdatedAt(v time.Time) *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WelfareBalanceUpsertBulk) UpdateUpdatedAt() *WelfareBalanceUpsertBulk {
	return u.Update(func(s *WelfareBalanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WelfareBalanceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WelfareBalanceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WelfareBalanceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WelfareBalanceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
