// Code generated by ent, DO NOT EDIT.

package usageriskreport

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usageriskreport type in the database.
	Label = "usage_risk_report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "report_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldReportDate holds the string denoting the report_date field in the database.
	FieldReportDate = "report_date"
	// FieldPolicyVersion holds the string denoting the policy_version field in the database.
	FieldPolicyVersion = "policy_version"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldRuleHits holds the string denoting the rule_hits field in the database.
	FieldRuleHits = "rule_hits"
	// FieldEvidence holds the string denoting the evidence field in the database.
	FieldEvidence = "evidence"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldInvalidatedAt holds the string denoting the invalidated_at field in the database.
	FieldInvalidatedAt = "invalidated_at"
	// FieldStatusUpdatedBy holds the string denoting the status_updated_by field in the database.
	FieldStatusUpdatedBy = "status_updated_by"
	// FieldStatusUpdatedAt holds the string denoting the status_updated_at field in the database.
	FieldStatusUpdatedAt = "status_updated_at"
	// Table holds the table name of the usageriskreport in the database.
	Table = "usage_risk_reports"
)

// Columns holds all SQL columns for usageriskreport fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldGroupID,
	FieldReportDate,
	FieldPolicyVersion,
	FieldScore,
	FieldLevel,
	FieldRuleHits,
	FieldEvidence,
	FieldStatus,
	FieldInvalidatedAt,
	FieldStatusUpdatedBy,
	FieldStatusUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPolicyVersion holds the default value on creation for the "policy_version" field.
	DefaultPolicyVersion int64
	// DefaultScore holds the default value on creation for the "score" field.
	DefaultScore int
	// LevelValidator is a validator for the "level" field. It is called by the builders before save.
	LevelValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the UsageRiskReport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByReportDate orders the results by the report_date field.
func ByReportDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportDate, opts...).ToFunc()
}

// ByPolicyVersion orders the results by the policy_version field.
func ByPolicyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyVersion, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByInvalidatedAt orders the results by the invalidated_at field.
func ByInvalidatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvalidatedAt, opts...).ToFunc()
}

// ByStatusUpdatedBy orders the results by the status_updated_by field.
func ByStatusUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusUpdatedBy, opts...).ToFunc()
}

// ByStatusUpdatedAt orders the results by the status_updated_at field.
func ByStatusUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusUpdatedAt, opts...).ToFunc()
}
