// Code generated by ent, DO NOT EDIT.

package usageriskrollup

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usageriskrollup type in the database.
	Label = "usage_risk_rollup"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldBucketHour holds the string denoting the bucket_hour field in the database.
	FieldBucketHour = "bucket_hour"
	// FieldRequestCount holds the string denoting the request_count field in the database.
	FieldRequestCount = "request_count"
	// FieldInputTokensSum holds the string denoting the input_tokens_sum field in the database.
	FieldInputTokensSum = "input_tokens_sum"
	// FieldOutputTokensSum holds the string denoting the output_tokens_sum field in the database.
	FieldOutputTokensSum = "output_tokens_sum"
	// FieldCacheReadTokensSum holds the string denoting the cache_read_tokens_sum field in the database.
	FieldCacheReadTokensSum = "cache_read_tokens_sum"
	// FieldCostUsdSum holds the string denoting the cost_usd_sum field in the database.
	FieldCostUsdSum = "cost_usd_sum"
	// FieldOccupiedMsSum holds the string denoting the occupied_ms_sum field in the database.
	FieldOccupiedMsSum = "occupied_ms_sum"
	// FieldNonWhitelistedUaCount holds the string denoting the non_whitelisted_ua_count field in the database.
	FieldNonWhitelistedUaCount = "non_whitelisted_ua_count"
	// FieldComputedAt holds the string denoting the computed_at field in the database.
	FieldComputedAt = "computed_at"
	// Table holds the table name of the usageriskrollup in the database.
	Table = "user_usage_metrics_rollup"
)

// Columns holds all SQL columns for usageriskrollup fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldGroupID,
	FieldBucketHour,
	FieldRequestCount,
	FieldInputTokensSum,
	FieldOutputTokensSum,
	FieldCacheReadTokensSum,
	FieldCostUsdSum,
	FieldOccupiedMsSum,
	FieldNonWhitelistedUaCount,
	FieldComputedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequestCount holds the default value on creation for the "request_count" field.
	DefaultRequestCount int
	// DefaultInputTokensSum holds the default value on creation for the "input_tokens_sum" field.
	DefaultInputTokensSum int64
	// DefaultOutputTokensSum holds the default value on creation for the "output_tokens_sum" field.
	DefaultOutputTokensSum int64
	// DefaultCacheReadTokensSum holds the default value on creation for the "cache_read_tokens_sum" field.
	DefaultCacheReadTokensSum int64
	// DefaultCostUsdSum holds the default value on creation for the "cost_usd_sum" field.
	DefaultCostUsdSum float64
	// DefaultOccupiedMsSum holds the default value on creation for the "occupied_ms_sum" field.
	DefaultOccupiedMsSum int64
	// DefaultNonWhitelistedUaCount holds the default value on creation for the "non_whitelisted_ua_count" field.
	DefaultNonWhitelistedUaCount int
	// DefaultComputedAt holds the default value on creation for the "computed_at" field.
	DefaultComputedAt func() time.Time
)

// OrderOption defines the ordering options for the UsageRiskRollup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByBucketHour orders the results by the bucket_hour field.
func ByBucketHour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucketHour, opts...).ToFunc()
}

// ByRequestCount orders the results by the request_count field.
func ByRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestCount, opts...).ToFunc()
}

// ByInputTokensSum orders the results by the input_tokens_sum field.
func ByInputTokensSum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokensSum, opts...).ToFunc()
}

// ByOutputTokensSum orders the results by the output_tokens_sum field.
func ByOutputTokensSum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokensSum, opts...).ToFunc()
}

// ByCacheReadTokensSum orders the results by the cache_read_tokens_sum field.
func ByCacheReadTokensSum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadTokensSum, opts...).ToFunc()
}

// ByCostUsdSum orders the results by the cost_usd_sum field.
func ByCostUsdSum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostUsdSum, opts...).ToFunc()
}

// ByOccupiedMsSum orders the results by the occupied_ms_sum field.
func ByOccupiedMsSum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccupiedMsSum, opts...).ToFunc()
}

// ByNonWhitelistedUaCount orders the results by the non_whitelisted_ua_count field.
func ByNonWhitelistedUaCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNonWhitelistedUaCount, opts...).ToFunc()
}

// ByComputedAt orders the results by the computed_at field.
func ByComputedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComputedAt, opts...).ToFunc()
}
